import { notFound } from "next/navigation";
import Link from "@/components/NativeLink";
import { InnerPage } from "@/components/InnerPage";
import { ConsultationForm } from "@/components/ConsultationForm";
import { ContactPage } from "@/components/ContactPage";
import { ProgramFinder } from "@/components/ProgramFinder";
import { UniversityCatalog } from "@/components/UniversityCatalog";
import { getFaqs,getPrograms,getReviews,getServices,getSettings,getUniversities } from "@/lib/content";
import { languageLabels,localizeFaqs,localizeService,pageIntro,requestText } from "@/lib/i18n";
export const dynamic="force-dynamic";
const pages:Record<string,{title:string;lead:string;body:string[]}>= {
  "hakkimizda":{title:"Güven, açıklık ve özen üzerine kurulu danışmanlık.",lead:"TD Danışmanlık; eğitim ve resmî işlemlerde karmaşık adımları anlaşılır, takip edilebilir bir yolculuğa dönüştürür.",body:["Her danışanın hedefi ve koşulları farklıdır. Bu nedenle sürece hazır cevaplarla değil, dikkatli bir ihtiyaç analiziyle başlarız.","Sunduğumuz bilgi ve yönlendirmeleri güncel kaynaklara göre değerlendirir; başvurunun her aşamasında şeffaf iletişimi koruruz."]},
  "gizlilik-politikasi":{title:"Gizlilik Politikası",lead:"Kişisel verilerinizin güvenliği ve şeffaf biçimde işlenmesi bizim için önceliklidir.",body:["İletişim ve danışmanlık formları aracılığıyla paylaştığınız bilgiler yalnızca talebinizi değerlendirmek, sizinle iletişime geçmek ve hizmet sunmak amacıyla kullanılır.","Verileriniz yetkisiz erişime karşı uygun teknik ve idari tedbirlerle korunur; yasal zorunluluklar dışında üçüncü kişilerle paylaşılmaz.","Verilerinize ilişkin talepleriniz için info@tddanismanlik.com adresinden bizimle iletişime geçebilirsiniz."]},
  "kvkk-aydinlatma-metni":{title:"KVKK Aydınlatma Metni",lead:"6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamındaki bilgilendirme metni.",body:["Kimlik ve iletişim bilgileriniz; danışmanlık talebinizi almak, sizinle iletişim kurmak, hizmet süreçlerini yürütmek ve yasal yükümlülükleri yerine getirmek amacıyla işlenebilir.","Kişisel verileriniz, açık rızanız veya kanunda belirtilen hukuki sebepler doğrultusunda ve amaçla sınırlı olarak saklanır.","KVKK’nın 11. maddesi kapsamındaki haklarınızı kullanmak için info@tddanismanlik.com adresine başvurabilirsiniz. Nihai hukuki metin, şirket bilgilerinin tamamlanmasının ardından hukuk danışmanınız tarafından gözden geçirilmelidir."]},
  "cerez-politikasi":{title:"Çerez Politikası",lead:"Sitemizde hangi çerezlerin neden kullanıldığını açıkça anlatıyoruz.",body:["Zorunlu çerezler sitenin güvenli ve doğru çalışması için gereklidir. Analitik ve pazarlama çerezleri yalnızca onayınızla etkinleştirilir.","Tercihlerinizi çerez bildirimindeki seçeneklerden yönetebilir veya tarayıcınız üzerinden silebilirsiniz."]},
  "kullanim-sartlari":{title:"Kullanım Şartları",lead:"Web sitemizi kullanırken geçerli olan temel koşullar.",body:["Sitede sunulan bilgiler genel bilgilendirme amaçlıdır ve kişiye özel hukuki görüş yerine geçmez. Güncel ve kişisel değerlendirme için danışmanlık talebi oluşturabilirsiniz.","İçeriklerin izinsiz çoğaltılması ve ticari amaçla kullanılması yasaktır."]},
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug==="tesekkurler")return{title:"Talebiniz Alındı | TD Danışmanlık",robots:{index:false,follow:false}};if(slug==="danismanlik-talebi")return{title:"Danışmanlık Talebi | TD Danışmanlık",description:"Eğitim ve resmî işlemler için danışmanlık talebi oluşturun."};if(slug==="iletisim")return{title:"İletişim ve Yol Tarifi | TD Danışmanlık",description:"Yeşilköy İstanbul ofisimiz, telefon, WhatsApp ve Google Maps yol tarifi."};const sectionTitles:Record<string,string>={hizmetler:"Hizmetler",universiteler:"Türkiye Üniversiteleri",bolumler:"Bölümler",surec:"Çalışma Sürecimiz",yorumlar:"Danışan Görüşleri",sss:"Sık Sorulan Sorular"};if(sectionTitles[slug])return{title:`${sectionTitles[slug]} | TD Danışmanlık`};const page=pages[slug];return page?{title:`${page.title} | TD Danışmanlık`,description:page.lead}:{};}
export default async function GenericPage({params,searchParams}:{params:Promise<{locale:string;slug:string}>;searchParams:Promise<{page?:string}>}){const [{locale,slug},query]=await Promise.all([params,searchParams]);const initialPage=Math.max(1,Number.parseInt(query.page||"1",10)||1);const [settings,services,universities,programs]=await Promise.all([getSettings(),getServices(),getUniversities(),getPrograms()]);const t=languageLabels(locale),request=requestText(locale);if(slug==="danismanlik-talebi")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.request}]}><main className="request-page"><section><p className="section-index">{t.request}</p><h1>{request.title1}<br/><em>{request.title2}</em></h1><p>{request.lead}</p><div className="request-points"><span><b>01</b>{request.point1}</span><span><b>02</b>{request.point2}</span><span><b>03</b>{request.point3}</span></div></section><ConsultationForm {...{services,universities,programs,locale}}/></main></InnerPage>;
  if(slug==="iletisim")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:"İletişim"}]}><ContactPage settings={settings} locale={locale}/></InnerPage>;
  if(slug==="tesekkurler")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:request.thanksTitle}]}><main className="thanks-page"><span>✓</span><p className="section-index">{request.thanksKicker}</p><h1>{request.thanksTitle}</h1><p>{request.thanksBody}</p><div><Link className="button button-dark" href={`/${locale}`}>{request.home}</Link>{settings.whatsapp&&<a className="button button-primary" href={`https://wa.me/${settings.whatsapp.replace(/\D/g,"")}`}>{request.whatsapp} ↗</a>}</div></main></InnerPage>;
  if(slug==="hizmetler")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.services}]}><main className="listing-page"><header><p className="elab-kicker">TD Danışmanlık / Hizmetler</p><h1>{pageIntro(locale,"hizmetler")[0]}</h1><p>{pageIntro(locale,"hizmetler")[1]}</p></header><div className="listing-grid">{services.map((item,i)=>{const s=localizeService(locale,item);return <Link key={s.id} href={`/${locale}/hizmetler/${s.slug}`}><span>{String(i+1).padStart(2,"0")}</span><h2>{s.title}</h2><p>{s.summary}</p><b>{t.viewService} ↗</b></Link>})}</div></main></InnerPage>;
  if(slug==="universiteler")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.universities}]}><main className="listing-page"><header><p className="elab-kicker">Türkiye üniversiteleri</p><h1>{pageIntro(locale,"universiteler")[0]}</h1><p>{pageIntro(locale,"universiteler")[1]}</p></header><UniversityCatalog universities={universities} locale={locale} initialPage={initialPage}/><p className="catalog-source">Kurum adları <a href="https://www.turkiye.gov.tr/universite-hizmet-listesi" target="_blank" rel="noopener noreferrer">e-Devlet üniversite listesinden</a> kontrol edilmiştir. Şehir ve tür bilgileri kamuya açık <a href="https://egitimharitasi.org/universite" target="_blank" rel="noopener noreferrer">üniversite tablosuyla</a> karşılaştırılmıştır. Liste, tercih kılavuzu değildir.</p></main></InnerPage>;
  if(slug==="bolumler")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.programs}]}><main className="listing-page elab-finder"><header><p className="elab-kicker">Program seçenekleri</p><h1>{pageIntro(locale,"bolumler")[0]}</h1><p>{pageIntro(locale,"bolumler")[1]}</p></header><ProgramFinder programs={programs} universities={universities} whatsapp={settings.whatsapp} locale={locale}/></main></InnerPage>;
  if(slug==="surec")return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.process}]}><main className="listing-page"><header><p className="elab-kicker">Nasıl çalışıyoruz?</p><h1>{pageIntro(locale,"surec")[0]}</h1><p>{pageIntro(locale,"surec")[1]}</p></header><div className="process-page-grid">{[["01",t.meet,t.meetBody],["02",t.roadmap,t.roadmapBody],["03",t.application,t.applicationBody],["04",t.followup,t.followupBody]].map(([n,title,body])=><article key={n}><span>{n}</span><h2>{title}</h2><p>{body}</p></article>)}</div><Link className="elab-pill elab-pill-blue" href={`/${locale}/danismanlik-talebi`}>{t.request} ↗</Link></main></InnerPage>;
  if(slug==="sss"){const faqs=localizeFaqs(locale,await getFaqs());return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.faq}]}><main className="listing-page"><header><p className="elab-kicker">Merak edilenler</p><h1>{pageIntro(locale,"sss")[0]}</h1><p>{pageIntro(locale,"sss")[1]}</p></header><div className="faq-page-list">{faqs.map((faq,i)=><details key={faq.id}><summary><span>{String(i+1).padStart(2,"0")}</span>{faq.question}<b>＋</b></summary><p>{faq.answer}</p></details>)}</div></main></InnerPage>}
  if(slug==="yorumlar"){const reviews=await getReviews();return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.reviews}]}><main className="listing-page"><header><p className="elab-kicker">Danışan görüşleri</p><h1>{pageIntro(locale,"yorumlar")[0]}</h1><p>{pageIntro(locale,"yorumlar")[1]}</p></header>{reviews.length?<div className="review-page-grid">{reviews.map(r=><article key={r.id}><blockquote>“{r.quote}”</blockquote><div className="review-page-person"><span aria-hidden="true">{r.author.slice(0,1)}</span><p><strong>{r.author}</strong><small>{r.context}</small></p></div></article>)}</div>:<div className="empty-state">{locale==="tr"?"Henüz yayımlanmış danışan görüşü bulunmuyor.":locale==="en"?"No client feedback has been published yet.":locale==="ru"?"Отзывы клиентов пока не опубликованы.":"لم تُنشر آراء العملاء بعد."}</div>}</main></InnerPage>}
  const page=pages[slug];if(!page)notFound();return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:page.title}]}><main className="legal-page"><header><p className="section-index">TD DANIŞMANLIK</p><h1>{page.title}</h1><p>{page.lead}</p></header><article>{page.body.map(p=><p key={p}>{p}</p>)}<small>Son güncelleme: 4 Eylül 2026</small></article></main></InnerPage>}
