import { notFound } from "next/navigation";
import Link from "@/components/NativeLink";
import { InnerPage } from "@/components/InnerPage";
import { ConsultationForm } from "@/components/ConsultationForm";
import { ContactPage } from "@/components/ContactPage";
import { getPrograms,getServices,getSettings,getUniversities } from "@/lib/content";
export const dynamic="force-dynamic";
const pages:Record<string,{title:string;lead:string;body:string[]}>= {
  "hakkimizda":{title:"Güven, açıklık ve özen üzerine kurulu danışmanlık.",lead:"TD Danışmanlık; eğitim ve resmî işlemlerde karmaşık adımları anlaşılır, takip edilebilir bir yolculuğa dönüştürür.",body:["Her danışanın hedefi ve koşulları farklıdır. Bu nedenle sürece hazır cevaplarla değil, dikkatli bir ihtiyaç analiziyle başlarız.","Sunduğumuz bilgi ve yönlendirmeleri güncel kaynaklara göre değerlendirir; başvurunun her aşamasında şeffaf iletişimi koruruz."]},
  "gizlilik-politikasi":{title:"Gizlilik Politikası",lead:"Kişisel verilerinizin güvenliği ve şeffaf biçimde işlenmesi bizim için önceliklidir.",body:["İletişim ve danışmanlık formları aracılığıyla paylaştığınız bilgiler yalnızca talebinizi değerlendirmek, sizinle iletişime geçmek ve hizmet sunmak amacıyla kullanılır.","Verileriniz yetkisiz erişime karşı uygun teknik ve idari tedbirlerle korunur; yasal zorunluluklar dışında üçüncü kişilerle paylaşılmaz.","Verilerinize ilişkin talepleriniz için info@tddanismanlik.com adresinden bizimle iletişime geçebilirsiniz."]},
  "kvkk-aydinlatma-metni":{title:"KVKK Aydınlatma Metni",lead:"6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamındaki bilgilendirme metni.",body:["Kimlik ve iletişim bilgileriniz; danışmanlık talebinizi almak, sizinle iletişim kurmak, hizmet süreçlerini yürütmek ve yasal yükümlülükleri yerine getirmek amacıyla işlenebilir.","Kişisel verileriniz, açık rızanız veya kanunda belirtilen hukuki sebepler doğrultusunda ve amaçla sınırlı olarak saklanır.","KVKK’nın 11. maddesi kapsamındaki haklarınızı kullanmak için info@tddanismanlik.com adresine başvurabilirsiniz. Nihai hukuki metin, şirket bilgilerinin tamamlanmasının ardından hukuk danışmanınız tarafından gözden geçirilmelidir."]},
  "cerez-politikasi":{title:"Çerez Politikası",lead:"Sitemizde hangi çerezlerin neden kullanıldığını açıkça anlatıyoruz.",body:["Zorunlu çerezler sitenin güvenli ve doğru çalışması için gereklidir. Analitik ve pazarlama çerezleri yalnızca onayınızla etkinleştirilir.","Tercihlerinizi çerez bildirimindeki seçeneklerden yönetebilir veya tarayıcınız üzerinden silebilirsiniz."]},
  "kullanim-sartlari":{title:"Kullanım Şartları",lead:"Web sitemizi kullanırken geçerli olan temel koşullar.",body:["Sitede sunulan bilgiler genel bilgilendirme amaçlıdır ve kişiye özel hukuki görüş yerine geçmez. Güncel ve kişisel değerlendirme için danışmanlık talebi oluşturabilirsiniz.","İçeriklerin izinsiz çoğaltılması ve ticari amaçla kullanılması yasaktır."]},
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug==="tesekkurler")return{title:"Talebiniz Alındı | TD Danışmanlık",robots:{index:false,follow:false}};if(slug==="danismanlik-talebi")return{title:"Danışmanlık Talebi | TD Danışmanlık",description:"Eğitim ve resmî işlemler için danışmanlık talebi oluşturun."};if(slug==="iletisim")return{title:"İletişim ve Yol Tarifi | TD Danışmanlık",description:"Yeşilköy İstanbul ofisimiz, telefon, WhatsApp ve Google Maps yol tarifi."};const page=pages[slug];return page?{title:`${page.title} | TD Danışmanlık`,description:page.lead}:{};}
export default async function GenericPage({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const [settings,services,universities,programs]=await Promise.all([getSettings(),getServices(),getUniversities(),getPrograms()]);if(slug==="danismanlik-talebi")return <InnerPage settings={settings} locale={locale} crumbs={[{label:"Ana Sayfa",href:`/${locale}`},{label:"Danışmanlık Talebi"}]}><main className="request-page"><section><p className="section-index">DANIŞMANLIK TALEBİ</p><h1>İlk adımı<br/><em>birlikte atalım.</em></h1><p>Formu doldurun; ekibimiz talebinizi inceleyerek en kısa sürede sizinle iletişime geçsin.</p><div className="request-points"><span><b>01</b>İhtiyacınızı dinleriz</span><span><b>02</b>Uygun yolu belirleriz</span><span><b>03</b>Net bir plan sunarız</span></div></section><ConsultationForm {...{services,universities,programs,locale}}/></main></InnerPage>;
  if(slug==="iletisim")return <InnerPage settings={settings} locale={locale} crumbs={[{label:"Ana Sayfa",href:`/${locale}`},{label:"İletişim"}]}><ContactPage settings={settings} locale={locale}/></InnerPage>;
  if(slug==="tesekkurler")return <InnerPage settings={settings} locale={locale} crumbs={[{label:"Ana Sayfa",href:`/${locale}`},{label:"Teşekkürler"}]}><main className="thanks-page"><span>✓</span><p className="section-index">TALEBİNİZ ALINDI</p><h1>Teşekkür ederiz.</h1><p>Ekibimiz talebinizi inceleyerek en kısa sürede sizinle iletişime geçecektir.</p><div><Link className="button button-dark" href={`/${locale}`}>Ana sayfaya dön</Link>{settings.whatsapp&&<a className="button button-primary" href={`https://wa.me/${settings.whatsapp.replace(/\D/g,"")}`}>WhatsApp’tan hemen yazın ↗</a>}</div></main></InnerPage>;
  const page=pages[slug];if(!page)notFound();return <InnerPage settings={settings} locale={locale} crumbs={[{label:"Ana Sayfa",href:`/${locale}`},{label:page.title}]}><main className="legal-page"><header><p className="section-index">TD DANIŞMANLIK</p><h1>{page.title}</h1><p>{page.lead}</p></header><article>{page.body.map(p=><p key={p}>{p}</p>)}<small>Son güncelleme: 4 Eylül 2026</small></article></main></InnerPage>}
