"use client";

import { FormEvent, useState } from "react";
import Link from "@/components/NativeLink";

type Message={role:"assistant"|"user";text:string};
const copy={
  tr:{title:"TD Asistan",subtitle:"Üniversite ve işlemler için hızlı yanıt",welcome:"Merhaba. Üniversite başvurusu, bölüm seçimi, kayıt veya ikamet işlemleri hakkında sorunuzu yazabilirsiniz.",placeholder:"Sorunuzu yazın…",launch:"Sorunuzu yazın",send:"Gönder",open:"TD Asistanı aç",close:"Kapat",error:"Şu anda yanıt oluşturamadım. Lütfen WhatsApp üzerinden ekibimize yazın.",notice:"Yanıtlar genel bilgilendirmedir; güncel resmî koşullar başvuru öncesinde teyit edilir.",contact:"Danışmana ulaşın"},
  en:{title:"TD Assistant",subtitle:"Quick answers about study and procedures",welcome:"Hello. Ask about university applications, programs, registration or residence procedures.",placeholder:"Type your question…",launch:"Ask a question",send:"Send",open:"Open TD Assistant",close:"Close",error:"I could not answer right now. Please contact our team on WhatsApp.",notice:"Answers are general information; current official requirements are confirmed before applying.",contact:"Contact an adviser"},
  ru:{title:"TD Ассистент",subtitle:"Ответы об учёбе и процедурах",welcome:"Здравствуйте. Задайте вопрос о поступлении, программах, регистрации или виде на жительство.",placeholder:"Введите вопрос…",launch:"Задать вопрос",send:"Отправить",open:"Открыть TD Ассистент",close:"Закрыть",error:"Сейчас не удалось ответить. Напишите нашей команде в WhatsApp.",notice:"Ответы носят общий характер; официальные требования уточняются перед подачей.",contact:"Связаться с консультантом"},
  ar:{title:"مساعد TD",subtitle:"إجابات سريعة حول الدراسة والإجراءات",welcome:"مرحباً. اسأل عن التقديم للجامعات أو التخصصات أو التسجيل أو الإقامة.",placeholder:"اكتب سؤالك…",launch:"اطرح سؤالاً",send:"إرسال",open:"افتح مساعد TD",close:"إغلاق",error:"تعذر إنشاء إجابة الآن. تواصل مع فريقنا عبر واتساب.",notice:"الإجابات معلومات عامة ويتم تأكيد الشروط الرسمية قبل التقديم.",contact:"تواصل مع مستشار"}
} as const;

export function AdvisorBot({locale="tr",whatsapp,questions}:{locale?:string;whatsapp:string;questions:string[]}) {
  const t=copy[(locale in copy?locale:"tr") as keyof typeof copy];
  const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[messages,setMessages]=useState<Message[]>([{role:"assistant",text:t.welcome}]);
  async function ask(question:string){const clean=question.trim();if(clean.length<2||loading)return;const history=messages.slice(-6);setMessages(current=>[...current,{role:"user",text:clean}]);setLoading(true);try{const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",body:JSON.stringify({question:clean,locale,history})});const result=await response.json() as {answer?:string};setMessages(current=>[...current,{role:"assistant",text:response.ok&&result.answer?result.answer:t.error}])}catch{setMessages(current=>[...current,{role:"assistant",text:t.error}])}finally{setLoading(false)}}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,field=form.elements.namedItem("question") as HTMLInputElement;const value=field.value;field.value="";void ask(value)}
  return <div className={`advisor-bot ${open?"is-open":""}`}><button className="advisor-launch" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-label={open?t.close:t.open}><span>TD</span><b>{open?t.close:t.launch}</b></button>{open&&<section className="advisor-panel" aria-label={t.title}><header><div><strong>{t.title}</strong><small>{t.subtitle}</small></div><button type="button" onClick={()=>setOpen(false)} aria-label={t.close}>×</button></header><div className="advisor-messages" aria-live="polite">{messages.map((message,index)=><p className={message.role} key={`${message.role}-${index}`}>{message.text}</p>)}{loading&&<p className="assistant advisor-typing"><i/><i/><i/></p>}</div>{messages.length===1&&<div className="advisor-suggestions">{questions.slice(0,3).map(question=><button type="button" onClick={()=>void ask(question)} key={question}>{question}</button>)}</div>}<form onSubmit={submit}><input name="question" maxLength={500} placeholder={t.placeholder} aria-label={t.placeholder} required/><button type="submit" disabled={loading}>{t.send}</button></form><footer><small>{t.notice}</small><Link href={whatsapp} target="_blank" rel="noopener noreferrer">{t.contact}</Link></footer></section>}</div>;
}
