"use client";
import { FormEvent, useState } from "react";
import type { Program, Service, University } from "@/lib/content";
import { localizeService } from "@/lib/i18n";
const formText={
 tr:{name:"Ad Soyad",phone:"Telefon",same:"Telefon ile aynıysa boş bırakın",service:"İlgilenilen hizmet",choose:"Seçin",preferred:"Tercih edilen iletişim",university:"Üniversite",program:"Bölüm",undecided:"Henüz karar vermedim",message:"Mesajınız",messageHint:"Size nasıl yardımcı olabileceğimizi kısaca anlatın.",notice:"KVKK Aydınlatma Metni",consent:"’ni okudum ve kişisel verilerimin iletişim amacıyla işlenmesini kabul ediyorum.",sending:"Gönderiliyor…",send:"Talebimi gönder",assurance:"Bilgileriniz yalnızca sizinle iletişime geçmek için kullanılır.",failed:"Talebiniz gönderilemedi."},
 en:{name:"Full name",phone:"Phone",same:"Leave blank if same as phone",service:"Service of interest",choose:"Choose",preferred:"Preferred contact",university:"University",program:"Program",undecided:"Not decided yet",message:"Your message",messageHint:"Briefly tell us how we can help.",notice:"KVKK privacy notice",consent:" — I have read it and consent to my personal data being processed to contact me.",sending:"Sending…",send:"Send request",assurance:"Your information is used only to contact you.",failed:"Your request could not be sent."},
 ru:{name:"Имя и фамилия",phone:"Телефон",same:"Оставьте пустым, если номер тот же",service:"Интересующая услуга",choose:"Выберите",preferred:"Предпочтительный способ связи",university:"Университет",program:"Программа",undecided:"Пока не решил(а)",message:"Ваше сообщение",messageHint:"Кратко расскажите, чем мы можем помочь.",notice:"Уведомление KVKK",consent:" — я ознакомился(-ась) и соглашаюсь на обработку данных для связи со мной.",sending:"Отправка…",send:"Отправить запрос",assurance:"Данные используются только для связи с вами.",failed:"Не удалось отправить запрос."},
 ar:{name:"الاسم الكامل",phone:"الهاتف",same:"اتركه فارغاً إذا كان الرقم نفسه",service:"الخدمة المطلوبة",choose:"اختر",preferred:"طريقة التواصل المفضلة",university:"الجامعة",program:"البرنامج",undecided:"لم أقرر بعد",message:"رسالتك",messageHint:"اشرح بإيجاز كيف يمكننا مساعدتك.",notice:"إشعار الخصوصية KVKK",consent:" — قرأته وأوافق على معالجة بياناتي الشخصية للتواصل معي.",sending:"جارٍ الإرسال…",send:"أرسل الطلب",assurance:"تُستخدم معلوماتك فقط للتواصل معك.",failed:"تعذر إرسال طلبك."}
} as const;

export function ConsultationForm({services,universities,programs,locale="tr"}:{services:Service[];universities:University[];programs:Program[];locale?:string}){const t=formText[(locale in formText?locale:"tr") as keyof typeof formText];const [state,setState]=useState<"idle"|"loading"|"error">("idle");const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState("loading");setError("");const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries()) as Record<string,unknown>;body.kvkk=form.get("kvkk")==="on";const res=await fetch("/api/consultations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await res.json() as {ok?:boolean;error?:string};if(res.ok&&result.ok)location.href=`/${locale}/tesekkurler`;else{setState("error");setError(locale==="tr"?result.error||t.failed:t.failed)}}return <form className="consultation-form" onSubmit={submit}><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><div className="form-grid"><label>{t.name} <span>*</span><input name="name" autoComplete="name" required minLength={2}/></label><label>{t.phone} <span>*</span><input name="phone" type="tel" autoComplete="tel" required placeholder="+90 …"/></label><label>WhatsApp<input name="whatsapp" type="tel" placeholder={t.same}/></label><label>E-mail <span>*</span><input name="email" type="email" autoComplete="email" required/></label><label>{t.service} <span>*</span><select name="service" required><option value="">{t.choose}</option>{services.map(s=><option key={s.id} value={s.title}>{localizeService(locale,s).title}</option>)}</select></label><label>{t.preferred}<select name="preferredContact"><option value="Telefon">{t.phone}</option><option>WhatsApp</option><option value="E-mail">E-mail</option></select></label><label>{t.university}<select name="university"><option value="">{t.undecided}</option>{universities.map(u=><option key={u.id}>{u.name}</option>)}</select></label><label>{t.program}<select name="program"><option value="">{t.undecided}</option>{programs.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label className="wide">{t.message} <span>*</span><textarea name="message" rows={6} required minLength={10} placeholder={t.messageHint}/></label></div><label className="consent"><input type="checkbox" name="kvkk" required/><span><a href={`/${locale}/kvkk-aydinlatma-metni`} target="_blank" rel="noreferrer">{t.notice}</a>{t.consent}</span></label>{state==="error"&&<p className="form-error" role="alert">{error}</p>}<button className="button button-primary submit-button" disabled={state==="loading"}>{state==="loading"?t.sending:t.send}<span>↗</span></button><small className="form-assurance">{t.assurance}</small></form>}
