"use client";

import { FormEvent, useState } from "react";

const copy={
  tr:{kicker:"E-POSTA",title:"E-posta ile iletişim",lead:"Talebinizi iletin; kaydınız güvenli biçimde oluşturulur ve ilgili ekibe yönlendirilir.",name:"Ad soyad",email:"E-posta",phone:"Telefon",message:"Mesajınız",consent:"KVKK Aydınlatma Metni’ni okudum ve iletişim amacıyla işlenmesini kabul ediyorum.",send:"Mesajı gönder",sending:"Gönderiliyor…",success:"Mesajınız alındı. Ekibimiz e-posta yoluyla dönüş sağlayacaktır.",error:"Mesaj gönderilemedi. Lütfen alanları kontrol edip tekrar deneyin."},
  en:{kicker:"EMAIL",title:"Contact us by email",lead:"Submit your request; it will be recorded securely and directed to the appropriate team.",name:"Full name",email:"Email",phone:"Phone",message:"Your message",consent:"I have read the personal data notice and consent to processing for contact purposes.",send:"Send message",sending:"Sending…",success:"Your message has been received. Our team will respond by email.",error:"The message could not be sent. Check the fields and try again."},
  ru:{kicker:"ЭЛЕКТРОННАЯ ПОЧТА",title:"Связаться по электронной почте",lead:"Отправьте запрос; он будет надежно зарегистрирован и передан соответствующей команде.",name:"Имя и фамилия",email:"Эл. почта",phone:"Телефон",message:"Сообщение",consent:"Я прочитал(а) уведомление о данных и согласен(на) на обработку для связи.",send:"Отправить",sending:"Отправка…",success:"Сообщение получено. Команда ответит по электронной почте.",error:"Не удалось отправить сообщение. Проверьте поля."},
  ar:{kicker:"البريد الإلكتروني",title:"التواصل عبر البريد الإلكتروني",lead:"أرسل طلبك؛ سيتم تسجيله بأمان وتوجيهه إلى الفريق المختص.",name:"الاسم الكامل",email:"البريد الإلكتروني",phone:"الهاتف",message:"رسالتك",consent:"قرأت إشعار حماية البيانات وأوافق على المعالجة لغرض التواصل.",send:"إرسال الرسالة",sending:"جارٍ الإرسال…",success:"تم استلام رسالتك وسيرد الفريق عبر البريد الإلكتروني.",error:"تعذر إرسال الرسالة. تحقق من الحقول وحاول مجدداً."}
} as const;

export function ContactEmailForm({locale="tr"}:{locale?:string}) {
  const t=copy[(locale in copy?locale:"tr") as keyof typeof copy];
  const [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("sending");const form=event.currentTarget,data=new FormData(form);const payload={name:data.get("name"),email:data.get("email"),phone:data.get("phone"),whatsapp:"",service:"E-posta iletişim",university:"",program:"",message:data.get("message"),preferredContact:"E-mail",kvkk:data.get("kvkk")==="on",website:data.get("website")};try{const response=await fetch("/api/consultations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {ok?:boolean};if(!response.ok||!result.ok)throw new Error();form.reset();setState("success")}catch{setState("error")}}
  return <section className="contact-email"><div><p className="elab-kicker">{t.kicker}</p><h2>{t.title}</h2><p>{t.lead}</p></div><form onSubmit={submit}><label>{t.name}<input name="name" autoComplete="name" minLength={2} required/></label><div className="contact-email-row"><label>{t.email}<input name="email" type="email" autoComplete="email" required/></label><label>{t.phone}<input name="phone" type="tel" autoComplete="tel" placeholder="+90 …" required/></label></div><label>{t.message}<textarea name="message" minLength={10} rows={6} required/></label><label className="contact-email-consent"><input name="kvkk" type="checkbox" required/><span>{t.consent}</span></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/><button type="submit" disabled={state==="sending"}>{state==="sending"?t.sending:t.send}</button>{state==="success"&&<p className="contact-form-success" role="status">{t.success}</p>}{state==="error"&&<p className="contact-form-error" role="alert">{t.error}</p>}</form></section>;
}
