"use client";

import { FormEvent, useState } from "react";

const copy={
  tr:{title:"Bize e-posta gönderin",lead:"Sorunuzu bırakın; mesajınız yönetim paneline kaydedilir ve e-posta bildirim altyapısı etkinse doğrudan ekibimize iletilir.",name:"Ad soyad",email:"E-posta",phone:"Telefon",message:"Mesajınız",consent:"KVKK Aydınlatma Metni’ni okudum ve iletişim amacıyla işlenmesini kabul ediyorum.",send:"Mesajı gönder",sending:"Gönderiliyor…",success:"Mesajınız alındı. En kısa sürede e-posta yoluyla dönüş yapacağız.",error:"Mesaj gönderilemedi. Lütfen alanları kontrol edip tekrar deneyin."},
  en:{title:"Send us an email",lead:"Leave your question and our team will respond by email.",name:"Full name",email:"Email",phone:"Phone",message:"Your message",consent:"I have read the personal data notice and consent to processing for contact purposes.",send:"Send message",sending:"Sending…",success:"Your message has been received. We will reply by email.",error:"The message could not be sent. Check the fields and try again."},
  ru:{title:"Напишите нам",lead:"Оставьте вопрос, и наша команда ответит по электронной почте.",name:"Имя и фамилия",email:"Эл. почта",phone:"Телефон",message:"Сообщение",consent:"Я прочитал(а) уведомление о данных и согласен(на) на обработку для связи.",send:"Отправить",sending:"Отправка…",success:"Сообщение получено. Мы ответим по электронной почте.",error:"Не удалось отправить сообщение. Проверьте поля."},
  ar:{title:"أرسل لنا بريداً إلكترونياً",lead:"اترك سؤالك وسيرد فريقنا عبر البريد الإلكتروني.",name:"الاسم الكامل",email:"البريد الإلكتروني",phone:"الهاتف",message:"رسالتك",consent:"قرأت إشعار حماية البيانات وأوافق على المعالجة لغرض التواصل.",send:"إرسال الرسالة",sending:"جارٍ الإرسال…",success:"تم استلام رسالتك وسنرد عبر البريد الإلكتروني.",error:"تعذر إرسال الرسالة. تحقق من الحقول وحاول مجدداً."}
} as const;

export function ContactEmailForm({locale="tr"}:{locale?:string}) {
  const t=copy[(locale in copy?locale:"tr") as keyof typeof copy];
  const [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("sending");const form=event.currentTarget,data=new FormData(form);const payload={name:data.get("name"),email:data.get("email"),phone:data.get("phone"),whatsapp:"",service:"E-posta iletişim",university:"",program:"",message:data.get("message"),preferredContact:"E-mail",kvkk:data.get("kvkk")==="on",website:data.get("website")};try{const response=await fetch("/api/consultations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {ok?:boolean};if(!response.ok||!result.ok)throw new Error();form.reset();setState("success")}catch{setState("error")}}
  return <section className="contact-email"><div><p className="elab-kicker">E-POSTA</p><h2>{t.title}</h2><p>{t.lead}</p></div><form onSubmit={submit}><label>{t.name}<input name="name" autoComplete="name" minLength={2} required/></label><div className="contact-email-row"><label>{t.email}<input name="email" type="email" autoComplete="email" required/></label><label>{t.phone}<input name="phone" type="tel" autoComplete="tel" placeholder="+90 …" required/></label></div><label>{t.message}<textarea name="message" minLength={10} rows={6} required/></label><label className="contact-email-consent"><input name="kvkk" type="checkbox" required/><span>{t.consent}</span></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/><button type="submit" disabled={state==="sending"}>{state==="sending"?t.sending:t.send}</button>{state==="success"&&<p className="contact-form-success" role="status">{t.success}</p>}{state==="error"&&<p className="contact-form-error" role="alert">{t.error}</p>}</form></section>;
}
