/* eslint-disable @next/next/no-img-element -- Local, size-bounded photos avoid a Vinext next/image client-navigation hook error. */
import Link from "next/link";
import type { HomeCopy, Program, Review, Service, SiteSettings, University } from "@/lib/content";
import { ProgramFinder } from "./ProgramFinder";
import { CookieBanner } from "./CookieBanner";
import { ChatWidget } from "./ChatWidget";
import { ConsentAnalytics } from "./ConsentAnalytics";
import { SiteHeader } from "./SiteHeader";
import { WhatsAppIcon } from "./WhatsAppIcon";
import { MapEmbed } from "./MapEmbed";

type FAQ={id:number;question:string;answer:string;category:string;active:number;sortOrder:number};

export function PublicHome({settings,homeCopy,reviews,services,universities,programs,faqs,locale="tr"}:{settings:SiteSettings;homeCopy:HomeCopy;reviews:Review[];services:Service[];universities:University[];programs:Program[];faqs:FAQ[];locale?:string}) {
  const home=`/${locale}`;
  const whatsapp=`https://wa.me/${settings.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent("Merhaba TD Danışmanlık, hizmetleriniz hakkında bilgi almak istiyorum.")}`;
  const heroBreak=settings.heroTitle.indexOf(". ");
  const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
  const orgSchema={"@context":"https://schema.org","@type":"ProfessionalService",name:settings.siteName,email:settings.email,telephone:settings.phone,address:{"@type":"PostalAddress",streetAddress:settings.address,addressLocality:"İstanbul",addressCountry:"TR"},areaServed:"Türkiye"};
  return <div className="site-page elab-page" dir={locale==="ar"?"rtl":"ltr"} style={{"--primary":settings.primaryColor,"--accent":settings.accentColor,"--site-heading-font":settings.headingFont==="Newsreader"?"var(--font-serif)":settings.headingFont==="IBM Plex Sans"?"var(--font-plex)":"var(--font-sans)","--site-body-font":settings.bodyFont==="Newsreader"?"var(--font-serif)":settings.bodyFont==="IBM Plex Sans"?"var(--font-plex)":"var(--font-sans)"} as React.CSSProperties}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(orgSchema)}}/>
    <SiteHeader settings={settings} locale={locale}/>
    <main>
      <section className="elab-hero" aria-labelledby="hero-title">
        <div className="elab-hero-copy"><p className="elab-kicker">{homeCopy.heroEyebrow}</p><h1 id="hero-title">{heroBreak>=0?<><span className="elab-hero-first">{settings.heroTitle.slice(0,heroBreak+1)}</span><span className="elab-hero-second">{settings.heroTitle.slice(heroBreak+2)}</span></>:settings.heroTitle}</h1><p className="elab-hero-lead">{settings.heroDescription}</p><div className="elab-hero-actions"><Link className="elab-pill elab-pill-blue" href={`/${locale}/danismanlik-talebi`}>{settings.ctaText} <span>↗</span></Link><a className="elab-inline-link" href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp’tan yazın ↗</a></div></div>
        <div className="elab-hero-photo"><img src="/td-students.jpg" alt="Kampüste notlarını birlikte inceleyen öğrencileri gösteren temsili fotoğraf" loading="eager" fetchPriority="high" decoding="async"/><a className="elab-photo-credit" href="https://www.pexels.com/photo/photograph-of-a-group-of-friends-having-a-conversation-7972533/" target="_blank" rel="noopener noreferrer">Temsili görsel · George Pak / Pexels</a></div>
        <div className="elab-hero-tiles" aria-label="Danışmanlık alanlarımız"><div><strong>01</strong><span>Üniversite<br/>ve bölüm seçimi</span></div><div><strong>02</strong><span>Başvuru<br/>ve kayıt takibi</span></div><div><strong>03</strong><span>İkamet ve<br/>resmî işlemler</span></div></div>
      </section>

      <section className="elab-section elab-services" id="hizmetler"><div className="elab-section-head"><p className="elab-kicker">01 / Hizmetlerimiz</p><h2>{homeCopy.servicesTitle}</h2><p>{homeCopy.servicesIntro}</p></div><div className="elab-service-grid">{services.map((service,i)=><Link className={`elab-service-card elab-service-card-${i%4}`} href={`/${locale}/hizmetler/${service.slug}`} key={service.id}><div className="elab-service-card-top"><span>{String(i+1).padStart(2,"0")}</span><span>↗</span></div><div><h3>{service.title}</h3><p>{service.summary}</p><span className="elab-card-cta">Hizmeti inceleyin ↗</span></div></Link>)}</div></section>

      <section className="elab-section elab-about" id="hakkimizda"><div className="elab-about-main"><div><p className="elab-kicker">02 / Yaklaşımımız</p><h2>{homeCopy.aboutTitle}</h2><p>{homeCopy.aboutBody}</p><Link className="elab-pill elab-pill-neutral" href={`/${locale}/hakkimizda`}>Bizi tanıyın <span>↗</span></Link></div><div className="elab-about-photo"><img src="/td-campus.jpg" alt="Kampüs yolunda belgeleri inceleyen öğrencileri gösteren temsili fotoğraf" loading="lazy" decoding="async"/><span>Her yolculuk, iyi bir planla başlar.</span></div></div><div className="elab-principles"><article><span>01</span><h3>Önce dinleriz.</h3><p>Hedefinizi ve mevcut durumunuzu anlayarak başlarız.</p></article><article><span>02</span><h3>Açık anlatırız.</h3><p>Seçenekleri, belgeleri ve sonraki adımları netleştiririz.</p></article><article><span>03</span><h3>Takip ederiz.</h3><p>Başvuru boyunca gelişmeleri sizinle paylaşırız.</p></article></div></section>

      <section className="elab-section elab-finder" id="universiteler"><div className="elab-section-head"><p className="elab-kicker">03 / Eğitim seçenekleri</p><h2>{homeCopy.finderTitle}</h2><p>{homeCopy.finderIntro}</p></div><div className="elab-university-grid">{universities.map(university=><Link href={`/${locale}/universiteler/${university.slug}`} key={university.id}><span>{university.city}</span><strong>{university.name}</strong><b>Üniversiteyi inceleyin ↗</b></Link>)}</div><ProgramFinder programs={programs} universities={universities} whatsapp={settings.whatsapp} locale={locale}/></section>

      <section className="elab-section elab-process" id="surec"><div className="elab-section-head"><p className="elab-kicker">04 / Nasıl çalışıyoruz?</p><h2>{homeCopy.processTitle}</h2><p>{homeCopy.processIntro}</p></div><div className="elab-process-grid">{[["01","Tanışma","Hedeflerinizi ve ihtiyaçlarınızı dinleriz."],["02","Yol haritası","Seçenekleri ve gerekli belgeleri belirleriz."],["03","Uygulama","Başvuru adımlarını birlikte yürütürüz."],["04","Takip","Gelişmeleri ve sonraki adımları paylaşırız."]].map(([number,title,description])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>

      <section className="elab-section elab-reviews" id="yorumlar"><div className="elab-section-head"><p className="elab-kicker">05 / Yorumlar</p><h2>{homeCopy.reviewsTitle}</h2><p>Gerçek danışan görüşleri geldikçe bu alanda yayımlanır. Aşağıdaki örnek metinler temsili içeriktir.</p></div><div className="elab-review-grid">{reviews.map(review=><article className="elab-review-card" key={review.id}><div className="elab-review-mark">“</div><blockquote>{review.quote}</blockquote><div><span className="elab-review-avatar">{review.author.slice(0,1)}</span><p><strong>{review.author}</strong><small>{review.context}</small></p></div>{Boolean(review.isExample)&&<span className="elab-example-badge">Temsili yorum</span>}</article>)}</div></section>

      <section className="elab-section elab-faq" id="sss"><div><p className="elab-kicker">06 / Sık sorulanlar</p><h2>Aklınızdaki sorular.</h2><p>Aradığınız yanıtı bulamadınız mı?</p><a className="elab-inline-link" href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp’tan sorun ↗</a></div><div className="elab-faq-list">{faqs.map((faq,i)=><details key={faq.id}><summary><span>{String(i+1).padStart(2,"0")}</span>{faq.question}<b>＋</b></summary><p>{faq.answer}</p></details>)}</div></section>

      <section className="elab-section elab-contact" id="iletisim"><div className="elab-contact-copy"><p className="elab-kicker">07 / İletişim</p><h2>{homeCopy.contactTitle}</h2><p>{homeCopy.contactBody}</p><div className="elab-contact-actions"><a className="elab-pill elab-pill-blue" href={whatsapp} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={19}/> WhatsApp’tan yazın</a><Link className="elab-pill elab-pill-neutral" href={`/${locale}/danismanlik-talebi`}>Formu doldurun ↗</Link></div><dl><div><dt>Telefon</dt><dd><a href={`tel:${settings.phone.replace(/\s/g,"")}`}>{settings.phone}</a></dd></div><div><dt>E-posta</dt><dd><a href={`mailto:${settings.email}`}>{settings.email}</a></dd></div><div><dt>Adres</dt><dd>{settings.address}</dd></div><div><dt>Çalışma saatleri</dt><dd>{settings.hours}</dd></div></dl><Link className="elab-inline-link" href={`/${locale}/iletisim`}>Tüm iletişim bilgileri ↗</Link></div><MapEmbed address={settings.address}/></section>
    </main>
    <footer className="elab-footer"><div className="elab-footer-grid"><div><Link className="elab-footer-brand" href={home}>TD <span>DANIŞMANLIK</span></Link><p>Eğitim ve resmî işlemlerde<br/>net, özenli danışmanlık.</p></div><div><strong>Keşfedin</strong><Link href={`${home}#hizmetler`}>Hizmetler</Link><Link href={`${home}#universiteler`}>Üniversiteler ve bölümler</Link><Link href={`${home}#surec`}>Sürecimiz</Link><Link href={`${home}#yorumlar`}>Yorumlar</Link><Link href={`${home}#sss`}>Sık sorulanlar</Link></div><div><strong>Kurumsal</strong><Link href={`/${locale}/hakkimizda`}>Hakkımızda</Link><Link href={`/${locale}/iletisim`}>İletişim</Link><Link href={`/${locale}/danismanlik-talebi`}>Danışmanlık talebi</Link><a href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp</a></div><div><strong>Yasal</strong><Link href={`/${locale}/kvkk-aydinlatma-metni`}>KVKK Aydınlatma Metni</Link><Link href={`/${locale}/gizlilik-politikasi`}>Gizlilik Politikası</Link><Link href={`/${locale}/cerez-politikasi`}>Çerez Politikası</Link><Link href={`/${locale}/kullanim-sartlari`}>Kullanım Şartları</Link></div></div><div className="elab-footer-bottom"><span>© {new Date().getFullYear()} TD Danışmanlık</span><span>Temsili fotoğraflar: <a href="https://www.pexels.com/photo/students-walking-together-7972492/" target="_blank" rel="noopener noreferrer">George Pak / Pexels</a></span></div></footer>
    <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp üzerinden TD Danışmanlık’a yazın"><WhatsAppIcon/></a>
    <div className="mobile-cta"><a href={`tel:${settings.phone.replace(/\s/g,"")}`}>Ara</a><a href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp</a><Link href={`/${locale}/danismanlik-talebi`}>Talep oluştur</Link></div>
    <ChatWidget whatsapp={settings.whatsapp}/><CookieBanner/><ConsentAnalytics measurementId={process.env.NEXT_PUBLIC_GA_ID}/>
  </div>;
}
