import Link from "next/link";
import type { Program, Service, SiteSettings, University } from "@/lib/content";
import { ProgramFinder } from "./ProgramFinder";
import { CookieBanner } from "./CookieBanner";
import { ChatWidget } from "./ChatWidget";
import { ConsentAnalytics } from "./ConsentAnalytics";

type FAQ={id:number;question:string;answer:string;category:string;active:number;sortOrder:number};
const localeLabels={tr:{services:"Hizmetler",universities:"Üniversiteler",process:"Süreç",about:"Hakkımızda",cta:"Danışmanlık alın"},en:{services:"Services",universities:"Universities",process:"Process",about:"About",cta:"Get consultation"},ru:{services:"Услуги",universities:"Университеты",process:"Процесс",about:"О нас",cta:"Консультация"},ar:{services:"الخدمات",universities:"الجامعات",process:"العملية",about:"من نحن",cta:"احصل على استشارة"}} as const;

export function PublicHome({settings,services,universities,programs,faqs,locale="tr"}:{settings:SiteSettings;services:Service[];universities:University[];programs:Program[];faqs:FAQ[];locale?:keyof typeof localeLabels}){
  const l=localeLabels[locale]??localeLabels.tr; const rtl=locale==="ar"; const whatsapp=settings.whatsapp?`https://wa.me/${settings.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent("Merhaba TD Danışmanlık, danışmanlık hizmetleriniz hakkında bilgi almak istiyorum.")}`:"/danismanlik-talebi";
  const headingFont=settings.headingFont==="Manrope"?"var(--font-sans)":"var(--font-serif)"; const bodyFont=settings.bodyFont==="Newsreader"?"var(--font-serif)":"var(--font-sans)";
  const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
  const orgSchema={"@context":"https://schema.org","@type":"ProfessionalService",name:settings.siteName,email:settings.email,telephone:settings.phone||undefined,areaServed:"Türkiye",availableLanguage:["Turkish","English","Russian","Arabic"]};
  return <div dir={rtl?"rtl":"ltr"} style={{"--primary":settings.primaryColor,"--accent":settings.accentColor,"--site-heading-font":headingFont,"--site-body-font":bodyFont} as React.CSSProperties}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(orgSchema)}}/>
    <header className="site-header"><Link className="brand" href={`/${locale}`} aria-label={`${settings.siteName} ana sayfa`}><span className="brand-mark">TD</span><span>{settings.siteName}<small>Eğitim · Yaşam · Gelecek</small></span></Link><nav className="desktop-nav" aria-label="Ana menü"><Link href="#hizmetler">{l.services}</Link><Link href="#universiteler">{l.universities}</Link><Link href="#surec">{l.process}</Link><Link href="#hakkimizda">{l.about}</Link></nav><div className="header-actions"><div className="language-menu"><span>{locale.toUpperCase()}⌄</span><div>{(["tr","en","ru","ar"] as const).map(code=><Link href={`/${code}`} key={code}>{code.toUpperCase()}</Link>)}</div></div><Link className="button button-dark" href={`/${locale}/danismanlik-talebi`}>{l.cta} <span>↗</span></Link></div></header>
    <main>
      <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span/> Türkiye’de eğitime ve hayata güvenli bir başlangıç</p><h1 id="hero-title">{settings.heroTitle.split(".").map((part,i)=><span key={i} className={i===1?"hero-serif":""}>{part.trim()}{i===0?".":part.trim()?".":""}{i===0&&<br/>}</span>)}</h1><p className="hero-lead">{settings.heroDescription}</p><div className="hero-actions"><Link className="button button-primary" href={`/${locale}/danismanlik-talebi`}>{settings.ctaText} <span>↗</span></Link><Link className="text-link" href="#hizmetler">Hizmetleri keşfedin <span>↓</span></Link></div><div className="trust-row" aria-label="Hizmet avantajları"><div><strong>4</strong><span>dilde iletişim</span></div><div><strong>8</strong><span>uzmanlık alanı</span></div><div><strong>01</strong><span>uçtan uca ekip</span></div></div></div>
        <div className="hero-visual" aria-label="Örnek danışmanlık yol haritası"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="route-card"><div className="route-head"><span className="route-kicker">Kişisel yol haritanız</span><span className="status-pill">Plan hazır</span></div><h2>Türkiye’de eğitim<br/>yolculuğunuz</h2><ol className="route-list"><li className="complete"><span>01</span><div><b>Hedef analizi</b><small>Profilinize uygun seçenekler</small></div><i>✓</i></li><li className="active"><span>02</span><div><b>Üniversite seçimi</b><small>Program ve bütçe eşleştirmesi</small></div><i>→</i></li><li><span>03</span><div><b>Başvuru ve kayıt</b><small>Evrak, başvuru ve süreç takibi</small></div></li><li><span>04</span><div><b>Türkiye’de yaşam</b><small>İkamet ve resmî işlemler</small></div></li></ol><div className="route-footer"><span>TD</span><p>Her adımda yanınızda.<small>TD danışmanınız</small></p></div></div><div className="mini-card mini-top"><span>✓</span><p><b>Belgeler kontrol edildi</b><small>Eksiksiz başvuru süreci</small></p></div><div className="mini-card mini-bottom"><b>TR · EN · RU · AR</b><small>Çok dilli destek</small></div></div>
      </section>
      <section className="service-strip" aria-label="Öne çıkan hizmetler"><p>Nasıl yardımcı olabiliriz?</p>{services.slice(0,3).map((s,i)=><Link key={s.id} href={`/${locale}/hizmetler/${s.slug}`}><span>0{i+1}</span>{s.title}<b>↗</b></Link>)}</section>
      <section className="section services-section" id="hizmetler"><div className="section-heading"><div><p className="section-index">01 — Uzmanlık alanlarımız</p><h2>Her önemli adım için<br/><em>tek, güvenilir ekip.</em></h2></div><p>Dosyanızı bir bütün olarak ele alır; eğitim, ikamet ve resmî süreçler arasında kopukluk yaşanmadan ilerlemenizi sağlarız.</p></div><div className="services-grid">{services.map(s=><Link className="service-card" href={`/${locale}/hizmetler/${s.slug}`} key={s.id}><div><span>{s.icon}</span><b>↗</b></div><h3>{s.title}</h3><p>{s.summary}</p><small>Detaylı bilgi</small></Link>)}</div></section>
      <section className="why-section" id="hakkimizda"><div className="why-manifesto"><p className="section-index light">02 — Neden TD?</p><h2>Karmaşık süreçleri,<br/><em>sizin için netleştiriyoruz.</em></h2><p>Karar vermeniz gereken noktaları açıklar, belgelerinizi özenle kontrol eder ve gelişmeleri zamanında paylaşırız.</p><Link href={`/${locale}/hakkimizda`}>Bizi tanıyın <span>↗</span></Link></div><div className="principles"><article><span>01</span><h3>Önce dinleriz.</h3><p>Herkese aynı çözümü değil, sizin hedeflerinize uyan yolu öneririz.</p></article><article><span>02</span><h3>Her adımı görünür kılarız.</h3><p>Nerede olduğunuzu ve sırada ne olduğunu her zaman bilirsiniz.</p></article><article><span>03</span><h3>Sonuca kadar takip ederiz.</h3><p>Başvurudan sonraki resmî işlemlerde de aynı ekiple devam edersiniz.</p></article></div></section>
      <section className="section finder-section" id="universiteler"><div className="section-heading"><div><p className="section-index">03 — Program keşfi</p><h2>Size uygun programı<br/><em>keşfetmeye başlayın.</em></h2></div><p>Örnek program kataloğunda şehir, derece ve eğitim diline göre arama yapın. Güncel koşullar için danışmanınızla teyitleşin.</p></div><ProgramFinder programs={programs} universities={universities} whatsapp={settings.whatsapp}/></section>
      <section className="process-section" id="surec"><div className="section-heading"><div><p className="section-index light">04 — Sürecimiz</p><h2>Dört net adımda<br/><em>yanınızdayız.</em></h2></div><p>Her aşama bir öncekinin çıktısı üzerine kurulur. Böylece beklenmedik durumları azaltır, size net bir plan sunarız.</p></div><div className="process-grid">{[["01","Tanışma","Hedeflerinizi ve mevcut durumunuzu dinleriz."],["02","Kişisel plan","Uygun seçenekleri ve gerekli adımları netleştiririz."],["03","Uygulama","Belgeleri hazırlar, başvuruları birlikte yürütürüz."],["04","Takip","Sonuçlanana kadar gelişmeleri düzenli paylaşırız."]].map((x,i)=><article key={x[0]} className={i===1?"highlighted":""}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
      <section className="section stories-section"><div className="section-heading"><div><p className="section-index">05 — Başarı hikâyeleri</p><h2>Yolculuğun her biri farklı.<br/><em>Yaklaşımımız hep özenli.</em></h2></div></div><div className="stories-grid"><article className="story-large"><div className="story-visual"><span>İST</span><small>41°01′N</small></div><div><span className="story-tag">Üniversite Başvurusu</span><h3>Doğru programdan eksiksiz kayda</h3><p>Akademik hedefler ve bütçe birlikte değerlendirilerek üç üniversitelik dengeli bir tercih planı oluşturuldu.</p><Link href={`/${locale}/vaka-calismalari/universite-basvurusu-istanbul`}>Hikâyeyi okuyun ↗</Link></div></article><article className="story-small"><span className="story-tag">İkamet İzni</span><h3>Belgeleri sadeleştiren net bir kontrol planı</h3><p>Başvuru öncesi kontrol ile süreçte oluşabilecek eksikler erkenden giderildi.</p><Link href={`/${locale}/vaka-calismalari/ikamet-izni-basvurusu`}>Detaylar ↗</Link></article></div></section>
      <section className="testimonial-section"><blockquote>“Sadece başvurumuzu yönetmediler; her aşamada ne yapmamız gerektiğini sakin ve anlaşılır biçimde anlattılar.”</blockquote><div><span className="avatar">A</span><p><b>Anonim danışan</b><small>Üniversite kayıt danışmanlığı</small></p><span className="stars" aria-label="5 üzerinden 5">★★★★★</span></div><small className="testimonial-note">Kimlik bilgisi paylaşılmadan yayımlanmıştır.</small></section>
      <section className="section faq-section" id="sss"><div className="faq-intro"><p className="section-index">06 — Sık sorulanlar</p><h2>Aklınızdaki sorulara<br/><em>net yanıtlar.</em></h2><p>Aradığınız yanıtı bulamadınız mı? Danışmanlık ekibimiz size yardımcı olmaya hazır.</p><a href={whatsapp} target={settings.whatsapp?"_blank":undefined} rel="noreferrer">WhatsApp’tan sorun ↗</a></div><div className="faq-list">{faqs.map((f,i)=><details key={f.id} open={i===0}><summary><span>0{i+1}</span>{f.question}<b>＋</b></summary><p>{f.answer}</p></details>)}</div></section>
      <section className="big-cta"><p>Bir sonraki adımınız net olsun.</p><h2>Size özel yol haritasını<br/><em>birlikte oluşturalım.</em></h2><div><Link className="button button-primary" href={`/${locale}/danismanlik-talebi`}>{settings.ctaText} <span>↗</span></Link><a href={whatsapp} target={settings.whatsapp?"_blank":undefined} rel="noreferrer">WhatsApp’tan yazın <span>↗</span></a></div></section>
    </main>
    <footer className="site-footer"><div className="footer-top"><div><Link className="brand footer-brand" href={`/${locale}`}><span className="brand-mark">TD</span><span>{settings.siteName}<small>Eğitim · Yaşam · Gelecek</small></span></Link><p>Eğitim, ikamet ve resmî işlemlerde güvenilir yol arkadaşınız.</p></div><div><b>Keşfedin</b><Link href="#hizmetler">Hizmetler</Link><Link href="#universiteler">Üniversiteler</Link><Link href="#surec">Süreç Rehberi</Link><Link href="#sss">Sık Sorulanlar</Link></div><div><b>İletişim</b>{settings.phone&&<a href={`tel:${settings.phone}`}>{settings.phone}</a>}<a href={`mailto:${settings.email}`}>{settings.email}</a><a href={whatsapp}>WhatsApp</a></div><div><b>Yasal</b><Link href={`/${locale}/kvkk-aydinlatma-metni`}>KVKK Aydınlatma Metni</Link><Link href={`/${locale}/gizlilik-politikasi`}>Gizlilik Politikası</Link><Link href={`/${locale}/cerez-politikasi`}>Çerez Politikası</Link><Link href={`/${locale}/kullanim-sartlari`}>Kullanım Şartları</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {settings.siteName}</span><span>Türkiye’de özenle hazırlandı.</span></div></footer>
    <a className="whatsapp-float" href={whatsapp} target={settings.whatsapp?"_blank":undefined} rel="noreferrer" aria-label="WhatsApp’tan yazın">W</a><div className="mobile-cta">{settings.phone&&<a href={`tel:${settings.phone}`}>Ara</a>}<a href={whatsapp}>WhatsApp</a><Link href={`/${locale}/danismanlik-talebi`}>Talep oluştur</Link></div><ChatWidget whatsapp={settings.whatsapp}/><CookieBanner/><ConsentAnalytics measurementId={process.env.NEXT_PUBLIC_GA_ID}/>
  </div>
}
