import { notFound } from "next/navigation";
import Link from "@/components/NativeLink";
import { InnerPage } from "@/components/InnerPage";
import { getProgram,getSettings } from "@/lib/content";
import { languageLabels } from "@/lib/i18n";

export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const p=await getProgram(slug);if(!p)return{};const name=locale==="tr"?p.name:(p.englishName||p.name);const description=locale==="en"?`${name} at ${p.universityName}. Review teaching language, duration, tuition guidance and application information.`:locale==="ru"?`${name} в ${p.universityName}. Язык обучения, срок, стоимость и информация о поступлении.`:locale==="ar"?`${name} في ${p.universityName}. معلومات لغة الدراسة والمدة والرسوم والتقديم.`:p.description;const title=`${name} | ${p.universityName} | TD Danışmanlık`;return{title,description,openGraph:{title,description},twitter:{card:"summary",title,description}}}

const copy={
 tr:{programs:"Bölümler",language:"Eğitim dili",duration:"Süre",fee:"Ücret",field:"Alan",about:"PROGRAM HAKKINDA",title:"Bölümü birlikte değerlendirelim.",note:"Ücret, burs, kontenjan ve kabul koşulları dönemsel olarak değişebilir. Başvurudan önce güncel resmî kaynağı kontrol ederiz.",source:"Resmî / referans kaynağını aç",action:"WhatsApp’tan bilgi alın"},
 en:{programs:"Programs",language:"Teaching language",duration:"Duration",fee:"Tuition",field:"Field",about:"ABOUT THE PROGRAM",title:"Let's review this program together.",note:"Fees, scholarships, places and admission conditions may change by term. We check the current official source before you apply.",source:"Open official / reference source",action:"Ask on WhatsApp"},
 ru:{programs:"Программы",language:"Язык обучения",duration:"Срок",fee:"Стоимость",field:"Направление",about:"О ПРОГРАММЕ",title:"Разберём программу вместе.",note:"Стоимость, стипендии, места и условия могут меняться. Перед подачей мы проверим официальный источник.",source:"Открыть официальный источник",action:"Спросить в WhatsApp"},
 ar:{programs:"البرامج",language:"لغة الدراسة",duration:"المدة",fee:"الرسوم",field:"المجال",about:"عن البرنامج",title:"لنقيّم البرنامج معاً.",note:"قد تتغير الرسوم والمنح والمقاعد وشروط القبول. نتحقق من المصدر الرسمي الحالي قبل التقديم.",source:"فتح المصدر الرسمي",action:"اسأل عبر واتساب"}
} as const;

export default async function ProgramPage({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const [settings,p]=await Promise.all([getSettings(),getProgram(slug)]);if(!p)notFound();const t=copy[(locale in copy?locale:"tr") as keyof typeof copy],nav=languageLabels(locale),displayName=locale==="tr"?p.name:(p.englishName||p.name),fee=p.tuitionFee.length>80||/doğrulanmadı/i.test(p.tuitionFee)?(locale==="en"?"Ask for current tuition":locale==="ru"?"Уточните актуальную стоимость":locale==="ar"?"اطلب الرسوم الحالية":"Güncel ücret için bilgi alın"):p.tuitionFee;const wa=settings.whatsapp?`https://wa.me/${settings.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(`Merhaba TD Danışmanlık,\n\n${p.universityName} bünyesindeki ${p.name} programı hakkında ücret ve başvuru bilgisi almak istiyorum.`)}`:`/${locale}/danismanlik-talebi`;return <InnerPage settings={settings} locale={locale} crumbs={[{label:nav.home,href:`/${locale}`},{label:t.programs,href:`/${locale}/bolumler`},{label:displayName}]}><main className="program-detail"><section><span className="degree-badge">{p.degreeType}</span><h1>{displayName}</h1>{locale==="tr"&&p.englishName&&p.englishName!==p.name&&<p className="program-english-name">{p.englishName}</p>}<p><Link href={`/${locale}/universiteler/${p.universitySlug}`}>{p.universityName}</Link></p><div>{p.language&&<span><small>{t.language}</small>{p.language}</span>}<span><small>{t.duration}</small>{p.duration}</span><span><small>{t.fee}</small>{fee}</span>{p.field&&<span><small>{t.field}</small>{p.field}</span>}</div></section><article><p className="section-index">{t.about}</p><h2>{t.title}</h2><p>{p.description}</p><p>{t.note}</p><a className="button button-primary" href={wa} target={settings.whatsapp?"_blank":undefined} rel="noreferrer">{t.action}</a></article></main></InnerPage>}
