import type { HomeCopy, Service, SiteSettings } from "./content";

export type Locale="tr"|"en"|"ru"|"ar";
export const locales:Locale[]=["tr","en","ru","ar"];
export const labels={
 tr:{menu:"Menü",services:"Hizmetler",universities:"Üniversiteler",programs:"Bölümler",process:"Süreç",reviews:"Yorumlar",faq:"SSS",contact:"İletişim",admin:"Yönetici girişi",request:"Danışmanlık talebi",whatsapp:"WhatsApp’tan yazın",allServices:"Tüm hizmetler",allUniversities:"Üniversiteyi filtrele",allPrograms:"Bölümleri ara",allProcess:"Sürecimizi inceleyin",allFaq:"Tüm sorular",allReviews:"Tüm görüşler",viewService:"Hizmeti inceleyin",viewUniversity:"Üniversiteyi inceleyin",about:"Bizi tanıyın",form:"Formu doldurun",contactAll:"Tüm iletişim bilgileri",phone:"Telefon",email:"E-posta",address:"Adres",askWhatsapp:"WhatsApp’tan sorun",footerDiscover:"Keşfedin",footerCorporate:"Kurumsal",footerLegal:"Yasal",home:"Ana sayfa",first:"Önce dinleriz.",second:"Açık anlatırız.",third:"Takip ederiz.",firstBody:"Hedefinizi ve mevcut durumunuzu anlayarak başlarız.",secondBody:"Seçenekleri, belgeleri ve sonraki adımları netleştiririz.",thirdBody:"Başvuru boyunca gelişmeleri sizinle paylaşırız.",qPrompt:"Aklınızdaki sorular.",qLead:"Aradığınız yanıtı bulamadınız mı?",meet:"Tanışma",roadmap:"Yol haritası",application:"Uygulama",followup:"Takip",meetBody:"Hedeflerinizi ve ihtiyaçlarınızı dinleriz.",roadmapBody:"Seçenekleri ve gerekli belgeleri belirleriz.",applicationBody:"Başvuru adımlarını birlikte yürütürüz.",followupBody:"Gelişmeleri ve sonraki adımları paylaşırız.",serviceKicker:"Hizmetlerimiz",aboutKicker:"Yaklaşımımız",educationKicker:"Eğitim seçenekleri",processKicker:"Nasıl çalışıyoruz?",reviewKicker:"Yorumlar",faqKicker:"Sık sorulanlar",contactKicker:"İletişim"},
 en:{menu:"Menu",services:"Services",universities:"Universities",programs:"Programs",process:"Our process",reviews:"Reviews",faq:"FAQ",contact:"Contact",admin:"Admin sign in",request:"Request a consultation",whatsapp:"Message on WhatsApp",allServices:"All services",allUniversities:"Browse universities",allPrograms:"Explore programs",allProcess:"How we work",allFaq:"All questions",allReviews:"All reviews",viewService:"View service",viewUniversity:"View university",about:"About us",form:"Fill out the form",contactAll:"All contact details",phone:"Phone",email:"Email",address:"Address",askWhatsapp:"Ask on WhatsApp",footerDiscover:"Explore",footerCorporate:"Company",footerLegal:"Legal",home:"Home",first:"We listen first.",second:"We explain clearly.",third:"We stay with you.",firstBody:"We start by understanding your goals and situation.",secondBody:"We clarify options, documents and next steps.",thirdBody:"We keep you updated throughout the application.",qPrompt:"Your questions, answered.",qLead:"Still looking for an answer?",meet:"Introduction",roadmap:"Roadmap",application:"Application",followup:"Follow-up",meetBody:"We listen to your goals and needs.",roadmapBody:"We identify options and required documents.",applicationBody:"We guide each application step.",followupBody:"We share updates and next steps.",serviceKicker:"Our services",aboutKicker:"Our approach",educationKicker:"Education options",processKicker:"How we work",reviewKicker:"Reviews",faqKicker:"Common questions",contactKicker:"Contact"},
 ru:{menu:"Меню",services:"Услуги",universities:"Университеты",programs:"Программы",process:"Этапы работы",reviews:"Отзывы",faq:"Вопросы",contact:"Контакты",admin:"Вход администратора",request:"Запросить консультацию",whatsapp:"Написать в WhatsApp",allServices:"Все услуги",allUniversities:"Поиск университетов",allPrograms:"Найти программы",allProcess:"Как мы работаем",allFaq:"Все вопросы",allReviews:"Все отзывы",viewService:"Подробнее об услуге",viewUniversity:"Подробнее об университете",about:"О нас",form:"Заполнить форму",contactAll:"Контактная информация",phone:"Телефон",email:"Эл. почта",address:"Адрес",askWhatsapp:"Спросить в WhatsApp",footerDiscover:"Разделы",footerCorporate:"Компания",footerLegal:"Правовая информация",home:"Главная",first:"Сначала слушаем.",second:"Объясняем понятно.",third:"Сопровождаем.",firstBody:"Сначала узнаём о ваших целях и обстоятельствах.",secondBody:"Разъясняем варианты, документы и дальнейшие шаги.",thirdBody:"Сообщаем о ходе подачи заявления.",qPrompt:"Ответы на ваши вопросы.",qLead:"Не нашли ответ?",meet:"Знакомство",roadmap:"План",application:"Подача",followup:"Сопровождение",meetBody:"Выслушиваем ваши цели и потребности.",roadmapBody:"Определяем варианты и документы.",applicationBody:"Помогаем на каждом этапе подачи.",followupBody:"Сообщаем новости и следующие шаги.",serviceKicker:"Наши услуги",aboutKicker:"Наш подход",educationKicker:"Варианты обучения",processKicker:"Как мы работаем",reviewKicker:"Отзывы",faqKicker:"Частые вопросы",contactKicker:"Контакты"},
 ar:{menu:"القائمة",services:"الخدمات",universities:"الجامعات",programs:"البرامج",process:"خطوات العمل",reviews:"الآراء",faq:"الأسئلة",contact:"اتصل بنا",admin:"دخول الإدارة",request:"طلب استشارة",whatsapp:"راسلنا عبر واتساب",allServices:"كل الخدمات",allUniversities:"تصفح الجامعات",allPrograms:"استكشف البرامج",allProcess:"كيف نعمل",allFaq:"كل الأسئلة",allReviews:"كل الآراء",viewService:"تفاصيل الخدمة",viewUniversity:"تفاصيل الجامعة",about:"تعرّف علينا",form:"املأ النموذج",contactAll:"كل معلومات التواصل",phone:"الهاتف",email:"البريد الإلكتروني",address:"العنوان",askWhatsapp:"اسأل عبر واتساب",footerDiscover:"استكشف",footerCorporate:"عن الشركة",footerLegal:"قانوني",home:"الرئيسية",first:"نستمع أولاً.",second:"نشرح بوضوح.",third:"نتابع معك.",firstBody:"نبدأ بفهم أهدافك وظروفك.",secondBody:"نوضح الخيارات والمستندات والخطوات التالية.",thirdBody:"نبقيك على اطلاع خلال الطلب.",qPrompt:"إجابات لأسئلتك.",qLead:"لم تجد الإجابة؟",meet:"التعارف",roadmap:"الخطة",application:"التقديم",followup:"المتابعة",meetBody:"نستمع إلى أهدافك واحتياجاتك.",roadmapBody:"نحدد الخيارات والمستندات المطلوبة.",applicationBody:"نرشدك في مراحل التقديم.",followupBody:"نشارك المستجدات والخطوات التالية.",serviceKicker:"خدماتنا",aboutKicker:"نهجنا",educationKicker:"خيارات الدراسة",processKicker:"كيف نعمل",reviewKicker:"الآراء",faqKicker:"الأسئلة الشائعة",contactKicker:"اتصل بنا"}
} as const;

const homeTranslations:Record<Exclude<Locale,"tr">,{heroTitle:string;heroDescription:string;ctaText:string;homeCopy:HomeCopy}>={
 en:{heroTitle:"A clear process. A confident future.",heroDescription:"Structured support for university applications, enrolment and official procedures in Türkiye, with clear documentation, deadlines and responsibilities.",ctaText:"Submit a consultation request",homeCopy:{heroEyebrow:"TD Consultancy",servicesTitle:"Comprehensive education and official-procedure consultancy.",servicesIntro:"We manage scope, documentation and critical dates for program selection, enrolment, residence and related official procedures.",aboutTitle:"Every file requires an individual assessment.",aboutBody:"We review the applicant’s circumstances, documents and schedule before defining the appropriate process and responsibilities.",finderTitle:"University and program catalogue.",finderIntro:"Review universities and programs by city, degree, language and field, and verify current conditions through official sources.",processTitle:"Defined stages, consistent follow-up.",processIntro:"We establish the scope at the outset and report the status and responsibilities of each stage.",reviewsTitle:"Client feedback",contactTitle:"Consultancy and contact.",contactBody:"Submit your request concerning university, enrolment or official procedures. Our team will assess the scope and respond through the appropriate channel."}},
 ru:{heroTitle:"Понятный процесс. Уверенное будущее.",heroDescription:"Системное сопровождение поступления, зачисления и официальных процедур в Турции с чётким контролем документов, сроков и обязанностей.",ctaText:"Отправить запрос на консультацию",homeCopy:{heroEyebrow:"TD Danışmanlık",servicesTitle:"Комплексное сопровождение обучения и официальных процедур.",servicesIntro:"Мы управляем объёмом работы, документами и ключевыми сроками при выборе программы, зачислении, оформлении ВНЖ и других процедурах.",aboutTitle:"Каждое дело требует индивидуальной оценки.",aboutBody:"До начала работы мы анализируем обстоятельства, документы и сроки заявителя и определяем подходящий порядок действий.",finderTitle:"Каталог университетов и программ.",finderIntro:"Изучайте вузы и программы по городу, степени, языку и направлению и проверяйте актуальные условия в официальных источниках.",processTitle:"Определённые этапы и регулярный контроль.",processIntro:"В начале мы фиксируем объём работы и регулярно сообщаем о статусе и обязанностях на каждом этапе.",reviewsTitle:"Отзывы клиентов",contactTitle:"Консультации и контакты.",contactBody:"Отправьте запрос по вопросам поступления, зачисления или официальных процедур. Команда оценит объём работы и свяжется с вами удобным способом."}},
 ar:{heroTitle:"إجراءات واضحة. مستقبل أكثر ثقة.",heroDescription:"دعم منظم للتقديم الجامعي والتسجيل والمعاملات الرسمية في تركيا، مع متابعة واضحة للمستندات والمواعيد والمسؤوليات.",ctaText:"إرسال طلب استشارة",homeCopy:{heroEyebrow:"TD للاستشارات",servicesTitle:"استشارات متكاملة للتعليم والمعاملات الرسمية.",servicesIntro:"ندير نطاق العمل والمستندات والمواعيد المهمة لاختيار البرنامج والتسجيل والإقامة والإجراءات الرسمية ذات الصلة.",aboutTitle:"كل ملف يحتاج إلى تقييم مستقل.",aboutBody:"نراجع ظروف المتقدم ومستنداته وجدوله الزمني قبل تحديد الإجراءات والمسؤوليات المناسبة.",finderTitle:"دليل الجامعات والبرامج.",finderIntro:"راجع الجامعات والبرامج حسب المدينة والدرجة واللغة والمجال، وتحقق من الشروط الحالية عبر المصادر الرسمية.",processTitle:"مراحل محددة ومتابعة منتظمة.",processIntro:"نحدد نطاق العمل منذ البداية ونقدم تحديثات منتظمة عن حالة كل مرحلة ومسؤولياتها.",reviewsTitle:"آراء العملاء",contactTitle:"الاستشارات والتواصل.",contactBody:"أرسل طلبك بشأن الجامعة أو التسجيل أو المعاملات الرسمية. سيقيّم فريقنا النطاق ويتواصل معك عبر القناة المناسبة."}}
};

const serviceTitles:Record<Exclude<Locale,"tr">,Record<string,string>>={
 en:{"universite-bolum-secimi":"University and program choice","kayit-sureci":"Applications and enrolment","ikamet-izni":"Residence permits","adres-kayit":"Address registration","calisma-izni":"Work permits","vatandaslik":"Citizenship procedures","tercume":"Translation services","denklik":"Diploma recognition"},
 ru:{"universite-bolum-secimi":"Выбор университета и программы","kayit-sureci":"Подача и зачисление","ikamet-izni":"Вид на жительство","adres-kayit":"Регистрация адреса","calisma-izni":"Разрешение на работу","vatandaslik":"Вопросы гражданства","tercume":"Перевод документов","denklik":"Признание диплома"},
 ar:{"universite-bolum-secimi":"اختيار الجامعة والتخصص","kayit-sureci":"التقديم والتسجيل","ikamet-izni":"تصريح الإقامة","adres-kayit":"تسجيل العنوان","calisma-izni":"تصريح العمل","vatandaslik":"إجراءات الجنسية","tercume":"ترجمة المستندات","denklik":"معادلة الشهادة"}
};
const serviceSummary:Record<Exclude<Locale,"tr">,string>={
 en:"We clarify the required documents, timing and next steps for your situation.",
 ru:"Поможем определить документы, сроки и следующие шаги с учётом вашей ситуации.",
 ar:"نوضح المستندات المطلوبة والمواعيد والخطوات التالية وفق حالتك."
};
const professionalLabels={
 tr:{meet:"Ön değerlendirme",roadmap:"Planlama",application:"Başvuru yönetimi",followup:"İzleme ve raporlama",meetBody:"Hedefler, mevcut belgeler ve uygunluk kriterleri değerlendirilir.",roadmapBody:"İş kapsamı, gerekli belgeler, sorumluluklar ve tarihler belirlenir.",applicationBody:"Başvuru adımları tanımlanan plana uygun biçimde yürütülür.",followupBody:"Gelişmeler, eksikler ve sonraki işlemler düzenli olarak raporlanır.",qPrompt:"Sık sorulan sorular.",qLead:"Genel bilgilendirmelerin dışında dosyanıza özel değerlendirme talep edebilirsiniz."},
 en:{meet:"Initial assessment",roadmap:"Planning",application:"Application management",followup:"Monitoring and reporting",meetBody:"Goals, available documents and eligibility criteria are assessed.",roadmapBody:"Scope, required documents, responsibilities and dates are defined.",applicationBody:"Application steps are carried out in line with the agreed plan.",followupBody:"Progress, missing items and next actions are reported regularly.",qPrompt:"Frequently asked questions.",qLead:"Request an individual assessment for matters beyond this general information."},
 ru:{meet:"Предварительная оценка",roadmap:"Планирование",application:"Ведение заявления",followup:"Контроль и отчётность",meetBody:"Оцениваются цели, имеющиеся документы и критерии соответствия.",roadmapBody:"Определяются объём работы, документы, обязанности и сроки.",applicationBody:"Этапы заявления выполняются в соответствии с согласованным планом.",followupBody:"О ходе работы, недостающих документах и следующих действиях сообщается регулярно.",qPrompt:"Часто задаваемые вопросы.",qLead:"По вопросам, выходящим за рамки общей информации, запросите индивидуальную оценку."},
 ar:{meet:"التقييم الأولي",roadmap:"التخطيط",application:"إدارة الطلب",followup:"المتابعة والتقارير",meetBody:"يتم تقييم الأهداف والمستندات المتاحة ومعايير الأهلية.",roadmapBody:"يتم تحديد نطاق العمل والمستندات والمسؤوليات والمواعيد.",applicationBody:"تُنفذ خطوات الطلب وفق الخطة المتفق عليها.",followupBody:"تُقدّم تقارير منتظمة عن التقدم والنواقص والخطوات التالية.",qPrompt:"الأسئلة الشائعة.",qLead:"يمكنك طلب تقييم فردي للمسائل التي تتجاوز هذه المعلومات العامة."},
} as const;
export function languageLabels(locale:string){const selected=(locales.includes(locale as Locale)?locale:"tr") as Locale;return {...labels[selected],...professionalLabels[selected]}}
const shortLabels={
 tr:{choice:"Üniversite ve bölüm seçimi",registration:"Kayıt süreci",residence:"İkamet izni",tile1:"Üniversite ve bölüm",tile2:"Başvuru ve kayıt",tile3:"İkamet ve resmî işlemler"},
 en:{choice:"University and program choice",registration:"Applications and enrolment",residence:"Residence permits",tile1:"University and program",tile2:"Applications and enrolment",tile3:"Residence and official steps"},
 ru:{choice:"Выбор университета и программы",registration:"Подача и зачисление",residence:"Вид на жительство",tile1:"Университет и программа",tile2:"Подача и зачисление",tile3:"ВНЖ и официальные процедуры"},
 ar:{choice:"اختيار الجامعة والتخصص",registration:"التقديم والتسجيل",residence:"تصريح الإقامة",tile1:"الجامعة والتخصص",tile2:"التقديم والتسجيل",tile3:"الإقامة والإجراءات الرسمية"}
} as const;
export function shortLanguageLabels(locale:string){return shortLabels[(locales.includes(locale as Locale)?locale:"tr") as Locale]}
export function localizeHome(locale:string,settings:SiteSettings,copy:HomeCopy,services:Service[]) {
 if(locale==="tr"||!homeTranslations[locale as Exclude<Locale,"tr">])return {settings,copy,services};
 const selected=locale as Exclude<Locale,"tr">;
 const translation=homeTranslations[selected];
 return {settings:{...settings,heroTitle:translation.heroTitle,heroDescription:translation.heroDescription,ctaText:translation.ctaText},copy:translation.homeCopy,services:services.map(service=>({...service,title:serviceTitles[selected][service.slug]||service.title,summary:serviceTitles[selected][service.slug]?serviceSummary[selected]:service.summary}))};
}
const faqTranslations:Record<Exclude<Locale,"tr">,Record<number,[string,string]>>={
 en:{
 1:["How do university applications work?","We review your academic background and goals, then plan suitable programs, documents and deadlines together."],
 2:["Which documents are needed for a residence permit?","Requirements depend on the application type and your circumstances. After an initial review, we prepare a current checklist."],
 3:["How long does a work permit take?","Timing depends on the application, employer and authority. We explain the likely stages after reviewing your file."],
 4:["Which languages do you offer?","We can communicate in Turkish, English, Russian and Arabic."],
 5:["Where can I find application deadlines?","Deadlines vary by university and program. We check the institution's official calendar with you."],
 6:["Can I apply from abroad?","Many universities accept online applications. We verify the current documents and steps with the institution."],
 7:["Is diploma recognition always required?","It depends on the application and institution. We review the official requirements for your case."],
 8:["Do documents need translation or notarisation?","Requirements vary by document and institution. We check the current list before arranging extra work."],
 9:["What happens in the first consultation?","We discuss your goals, documents, timeline and priorities, then outline the next steps."],
 10:["Are tuition fees on this site final?","No. Fees, scholarships and places change; always verify current figures with the university."],
 11:["Do you submit residence applications on my behalf?","We clarify the scope of support after reviewing your case. The final decision rests with the authority."],
 12:["Must I visit your office?","An initial discussion can take place by phone or online. We will tell you if in-person steps are needed."]},
 ru:{
 1:["Как подать заявление в университет?","Мы изучим ваши цели и образование, затем вместе составим список программ, документов и сроков."],
 2:["Какие документы нужны для вида на жительство?","Список зависит от типа заявления и вашей ситуации. После оценки подготовим актуальный перечень."],
 3:["Сколько длится оформление разрешения на работу?","Срок зависит от заявления, работодателя и ведомства. После проверки документов объясним этапы."],
 4:["На каких языках вы работаете?","Мы можем общаться на турецком, английском, русском и арабском языках."],
 5:["Где узнать сроки подачи?","Сроки различаются по вузам и программам. Вместе проверим официальный календарь."],
 6:["Можно ли подать заявление из-за рубежа?","Многие вузы принимают заявления онлайн. Уточним документы и шаги на сайте вуза."],
 7:["Всегда ли нужно признание диплома?","Это зависит от процедуры и вуза. Проверим официальные требования."],
 8:["Нужен ли перевод и нотариальное заверение?","Это зависит от документа и вуза. Сначала изучим актуальный список."],
 9:["Что обсуждается на первой консультации?","Ваши цели, документы, сроки и приоритеты. Затем определяем следующие шаги."],
 10:["Окончательна ли указанная плата за обучение?","Нет. Стоимость и стипендии меняются. Проверяйте актуальные данные у университета."],
 11:["Вы подаёте заявление на ВНЖ за меня?","Объём сопровождения определим после изучения дела. Решение принимает госорган."],
 12:["Обязательно ли приходить в офис?","Первую консультацию можно провести по телефону или онлайн. О личном визите сообщим заранее."]},
 ar:{
 1:["كيف أقدّم للجامعة؟","نراجع مؤهلاتك وأهدافك ثم نخطط للبرامج والمستندات والمواعيد معاً."],
 2:["ما المستندات المطلوبة للإقامة؟","تختلف حسب نوع الطلب وظروفك. بعد المراجعة نعد قائمة حديثة بالمطلوب."],
 3:["كم يستغرق تصريح العمل؟","تعتمد المدة على الطلب وصاحب العمل والجهة المختصة. نوضح المراحل بعد مراجعة ملفك."],
 4:["ما اللغات المتاحة؟","نتواصل بالتركية والإنجليزية والروسية والعربية."],
 5:["أين أجد مواعيد التقديم؟","تختلف حسب الجامعة والبرنامج. نتحقق معك من التقويم الرسمي."],
 6:["هل يمكنني التقديم من الخارج؟","تقبل جامعات كثيرة الطلبات عبر الإنترنت. نتحقق من المستندات والخطوات الرسمية."],
 7:["هل معادلة الشهادة مطلوبة دائماً؟","يعتمد ذلك على نوع الطلب والجهة. نراجع الشروط الرسمية لحالتك."],
 8:["هل يجب ترجمة المستندات وتصديقها؟","تختلف المتطلبات حسب المستند والجهة. نراجع القائمة الحالية أولاً."],
 9:["ماذا يحدث في الاستشارة الأولى؟","نتحدث عن أهدافك ومستنداتك ومواعيدك وأولوياتك، ثم نحدد الخطوات التالية."],
 10:["هل الرسوم الدراسية المذكورة نهائية؟","لا. تتغير الرسوم والمنح والمقاعد؛ تأكد من الأرقام الحالية لدى الجامعة."],
 11:["هل تقدمون طلب الإقامة نيابة عني؟","نوضح نطاق المساعدة بعد مراجعة حالتك. القرار النهائي للجهة المختصة."],
 12:["هل يجب زيارة المكتب؟","يمكن إجراء المحادثة الأولى هاتفياً أو عبر الإنترنت. نخبرك إذا لزم الحضور."]}
};
export function localizeFaqs<T extends {sortOrder:number;question:string;answer:string}>(locale:string,faqs:T[]):T[] {
 if(locale==="tr"||!faqTranslations[locale as Exclude<Locale,"tr">])return faqs;
 const translations=faqTranslations[locale as Exclude<Locale,"tr">];
 return faqs
   .filter(faq=>Boolean(translations[faq.sortOrder]))
   .map(faq=>({...faq,question:translations[faq.sortOrder][0],answer:translations[faq.sortOrder][1]}));
}
const pageIntros={
 en:{hizmetler:["Services tailored to your needs.","We plan applications, enrolment and official steps around your individual circumstances."],universiteler:["University guide.","Explore public and foundation universities by city, type and establishment year. Confirm admission conditions with the institution."],bolumler:["Find a program.","Filter the supplied catalogue by city, university, degree, language and field. Confirm current fees and admission conditions in the university’s official notice."],surec:["Know every step.","Your case is unique, but we keep the timing and responsibilities clear throughout."],yorumlar:["Notes from different journeys.","Short, personal accounts from application, enrolment and document processes."],sss:["Your questions, answered.","These answers are general guidance. We clarify the details of your case in a consultation."]},
 ru:{hizmetler:["Поддержка по вашему запросу.","Планируем поступление, оформление и официальные процедуры с учётом вашей ситуации."],universiteler:["Справочник университетов.","Изучайте государственные и частные вузы по городу, типу и году основания. Уточняйте условия в вузе."],bolumler:["Поиск программ.","Фильтруйте каталог по городу, вузу, степени, языку и направлению. Актуальные цены и условия уточняйте в официальных объявлениях вуза."],surec:["Понимайте каждый этап.","Каждое дело индивидуально, но сроки и задачи всегда остаются понятными."],yorumlar:["Заметки о разных путях.","Короткие личные истории о поступлении, регистрации и документах."],sss:["Ответы на ваши вопросы.","Это общая информация. Подробности вашей ситуации обсудим на консультации."]},
 ar:{hizmetler:["خدمات تناسب احتياجاتك.","نخطط للتقديم والتسجيل والإجراءات الرسمية وفق ظروفك الخاصة."],universiteler:["دليل الجامعات.","استكشف الجامعات الحكومية والوقفية حسب المدينة والنوع وسنة التأسيس. تحقق من شروط القبول لدى الجامعة."],bolumler:["ابحث عن برنامج.","صفِّ الكتالوج حسب المدينة والجامعة والدرجة واللغة والمجال. تحقق من الرسوم والشروط الحالية في الإعلان الرسمي للجامعة."],surec:["اعرف كل خطوة.","تختلف الحالات، لكننا نوضح المواعيد والمسؤوليات طوال العمل."],yorumlar:["ملاحظات من مسارات مختلفة.","تجارب شخصية قصيرة حول التقديم والتسجيل وإعداد المستندات."],sss:["إجابات لأسئلتك.","هذه معلومات عامة. نوضح تفاصيل حالتك خلال الاستشارة."]}
} as const;
export function pageIntro(locale:string,slug:keyof typeof pageIntros.en) {
 const fallback:Record<keyof typeof pageIntros.en,[string,string]>={hizmetler:["İhtiyacınıza uygun desteği bulun.","Başvuru, kayıt ve resmî işlemleri dosyanızın koşullarına göre planlarız."],universiteler:["Üniversite rehberi.","Devlet ve vakıf üniversitelerini şehir, tür ve kuruluş yılına göre keşfedin. Program ve kabul koşulları için kurumun güncel resmî duyurusunu kontrol edin."],bolumler:["Bölüm arayın.","Sağlanan kataloğu şehir, üniversite, derece, dil ve alana göre filtreleyin. Güncel ücret ve kabul koşulları için üniversitenin resmî duyurusunu esas alın."],surec:["Her adım belli olsun.","Başvurunuzun içeriği değişse de süreç boyunca neyin ne zaman yapılacağını birlikte netleştiririz."],yorumlar:["Farklı yolculuklardan kısa notlar.","Başvuru, kayıt ve belge süreçlerinde öne çıkan kişisel deneyimler."],sss:["Aklınızdaki sorular.","Yanıtlar genel bilgilendirme amaçlıdır. Dosyanıza özel koşulları görüşmede netleştiririz."]};
 return locale==="tr"?fallback[slug]:(pageIntros[locale as Exclude<Locale,"tr">]?.[slug]??fallback[slug]);
}
export function localizeService(locale:string,service:Service):Service {
 if(locale==="tr"||!serviceTitles[locale as Exclude<Locale,"tr">]?.[service.slug])return service;
 const selected=locale as Exclude<Locale,"tr">;
 return {...service,title:serviceTitles[selected][service.slug],summary:serviceSummary[selected],detail:serviceSummary[selected]};
}
const serviceDetailLabels={
 tr:{scope:"HİZMET KAPSAMI",scopeTitle:"Her ayrıntının yerli yerinde olduğu bir süreç.",note:"Dosyanız kişisel durumunuza göre değerlendirilir. Gerekli belgeler, tahmini aşamalar ve kritik tarihler ilk görüşmenin ardından netleştirilir.",how:"Süreç nasıl işler?",related:"İLGİLİ HİZMETLER",consult:"Danışmanlık alın",tagline:"Profesyonel süreç takibi",subtag:"Güncel bilgi · Şeffaf iletişim",steps:["İhtiyaç ve uygunluk değerlendirmesi","Gerekli belgelerin kontrolü","Başvuru planı ve hazırlık","Kurum sürecinin takibi","Sonuç ve sonraki adımlar"]},
 en:{scope:"SERVICE SCOPE",scopeTitle:"A clear process, down to the details.",note:"We review your case individually. Documents, expected stages and important dates become clear after the first conversation.",how:"How does it work?",related:"RELATED SERVICES",consult:"Request a consultation",tagline:"Professional case support",subtag:"Current information · Clear communication",steps:["Review your needs and eligibility","Check required documents","Plan and prepare the application","Track the institutional process","Review the result and next steps"]},
 ru:{scope:"ОБ УСЛУГЕ",scopeTitle:"Чёткий процесс с вниманием к деталям.",note:"Мы оцениваем вашу ситуацию индивидуально. Документы, этапы и важные сроки уточним после первой беседы.",how:"Как проходит работа?",related:"ДРУГИЕ УСЛУГИ",consult:"Запросить консультацию",tagline:"Сопровождение вашего дела",subtag:"Актуальная информация · Понятная связь",steps:["Оценка потребностей и условий","Проверка документов","Планирование и подготовка","Сопровождение процедуры","Результат и следующие шаги"]},
 ar:{scope:"نطاق الخدمة",scopeTitle:"عملية واضحة تهتم بالتفاصيل.",note:"نراجع حالتك بشكل فردي. نوضح المستندات والمراحل والمواعيد المهمة بعد المحادثة الأولى.",how:"كيف تسير العملية؟",related:"خدمات ذات صلة",consult:"اطلب استشارة",tagline:"متابعة مهنية للملف",subtag:"معلومات حديثة · تواصل واضح",steps:["تقييم الاحتياجات والأهلية","مراجعة المستندات المطلوبة","التخطيط والتحضير","متابعة الإجراءات","النتيجة والخطوات التالية"]}
} as const;
export function serviceDetailText(locale:string){return serviceDetailLabels[(locale in serviceDetailLabels?locale:"tr") as Locale]}
const universityDetailLabels={
 tr:{university:"Üniversiteler",public:"Devlet",foundation:"Vakıf",profile:"ÜNİVERSİTE PROFİLİ",city:"ŞEHİR",type:"TÜR",founded:"KURULUŞ",unknown:"Bilgi teyit edilmeli",consult:"Bu üniversite için bilgi alın",admission:"Başvuruya hazırlanırken",admissionBody:"Başvuru takvimi, kabul koşulları, dil yeterliliği ve ücretler programlara göre değişir. Seçtiğiniz bölümün o döneme ait resmî duyurusunu kontrol edin.",documents:"Belge kontrolü",documentsBody:"Diploma, transkript, pasaport, tercüme ve ek belgeler kişisel durumunuza göre istenebilir. Eksik işlemden kaçınmak için kurumun güncel listesini esas alırız.",support:"Dosyanıza özel yol",supportBody:"Program seçimi, başvuru ve kayıt adımlarını sizin hedefinize göre planlayabiliriz. Kesin kabul kararını üniversite verir.",programs:"İlgili bölümler",programNote:"Katalog, sağlanan üniversite veri kaynağındaki güncel program listesinden oluşturulmuştur. Ücret ve kontenjanı resmî duyurudan teyit edin.",atlas:"YÖK Atlas’ı aç",empty:"Bu üniversite için program kaydı bulunamadı. Güncel bölümleri YÖK Atlas’ta veya üniversitenin resmî sitesinde inceleyebilirsiniz.",bottomTitle:"Bu üniversiteyi mi düşünüyorsunuz?",bottomBody:"Hedefinizi ve belgelerinizi konuşalım; gereken adımları netleştirelim.",request:"Danışmanlık talebi",generic:"Türkiye'de bulunan bir üniversitedir. Program, ücret ve başvuru koşullarını kurumun güncel resmî duyurularından teyit edin."},
 en:{university:"Universities",public:"Public",foundation:"Foundation",profile:"UNIVERSITY PROFILE",city:"CITY",type:"TYPE",founded:"FOUNDED",unknown:"To be verified",consult:"Ask about this university",admission:"Preparing your application",admissionBody:"Deadlines, admission requirements, language proficiency and fees vary by program. Check the institution's current official notice.",documents:"Document review",documentsBody:"Diplomas, transcripts, passports, translations and other papers may be needed depending on your case. We work from the institution's current list.",support:"A plan for your case",supportBody:"We can help plan program selection, application and enrolment around your goals. The university makes the final admission decision.",programs:"Related programs",programNote:"Only programs entered by our team appear here. See official sources for the complete current list.",atlas:"Open YÖK Atlas",empty:"No verified program has been added for this university yet. Check YÖK Atlas or the university's official website.",bottomTitle:"Considering this university?",bottomBody:"Let's discuss your goals and documents, then clarify the next steps.",request:"Request a consultation",generic:"A university in Türkiye. Verify programs, fees and admission conditions in the institution's current official notices."},
 ru:{university:"Университеты",public:"Государственный",foundation:"Частный",profile:"ПРОФИЛЬ УНИВЕРСИТЕТА",city:"ГОРОД",type:"ТИП",founded:"ОСНОВАН",unknown:"Нужно уточнить",consult:"Узнать об этом университете",admission:"Подготовка к поступлению",admissionBody:"Сроки, условия, требования к языку и стоимость зависят от программы. Проверьте актуальное объявление вуза.",documents:"Проверка документов",documentsBody:"Могут понадобиться диплом, выписка оценок, паспорт, переводы и другие документы. Мы опираемся на актуальный список вуза.",support:"План для вашего дела",supportBody:"Поможем спланировать выбор программы, подачу и зачисление. Окончательное решение принимает университет.",programs:"Программы",programNote:"Здесь показаны только программы, добавленные нашей командой. Полный список смотрите в официальных источниках.",atlas:"Открыть YÖK Atlas",empty:"Подтверждённых программ этого вуза пока нет. Проверьте YÖK Atlas или официальный сайт.",bottomTitle:"Рассматриваете этот университет?",bottomBody:"Обсудим ваши цели и документы и определим следующие шаги.",request:"Запросить консультацию",generic:"Университет Турции. Проверяйте программы, стоимость и условия в актуальных официальных объявлениях."},
 ar:{university:"الجامعات",public:"حكومية",foundation:"وقفية",profile:"ملف الجامعة",city:"المدينة",type:"النوع",founded:"التأسيس",unknown:"تحتاج إلى تأكيد",consult:"اسأل عن هذه الجامعة",admission:"الاستعداد للتقديم",admissionBody:"تختلف المواعيد والشروط ومتطلبات اللغة والرسوم حسب البرنامج. راجع إعلان الجامعة الرسمي الحالي.",documents:"مراجعة المستندات",documentsBody:"قد تحتاج إلى شهادة وكشف درجات وجواز سفر وترجمات وغيرها حسب حالتك. نعتمد القائمة الحالية للجامعة.",support:"خطة تناسب ملفك",supportBody:"نساعد في تخطيط اختيار البرنامج والتقديم والتسجيل وفق أهدافك. قرار القبول النهائي للجامعة.",programs:"البرامج ذات الصلة",programNote:"تظهر هنا فقط البرامج التي أضافها فريقنا. راجع المصادر الرسمية للقائمة الكاملة الحالية.",atlas:"افتح YÖK Atlas",empty:"لم تتم إضافة برامج موثقة لهذه الجامعة بعد. راجع YÖK Atlas أو الموقع الرسمي.",bottomTitle:"هل تفكر في هذه الجامعة؟",bottomBody:"لنتحدث عن أهدافك ومستنداتك ونوضح الخطوات التالية.",request:"طلب استشارة",generic:"جامعة في تركيا. تحقق من البرامج والرسوم وشروط القبول في الإعلانات الرسمية الحالية."}
} as const;
export function universityDetailText(locale:string){return universityDetailLabels[(locale in universityDetailLabels?locale:"tr") as Locale]}
const requestLabels={
 tr:{title1:"İlk adımı",title2:"birlikte atalım.",lead:"Formu doldurun; ekibimiz talebinizi inceleyerek en kısa sürede sizinle iletişime geçsin.",point1:"İhtiyacınızı dinleriz",point2:"Uygun yolu belirleriz",point3:"Net bir plan sunarız",thanksKicker:"TALEBİNİZ ALINDI",thanksTitle:"Teşekkür ederiz.",thanksBody:"Ekibimiz talebinizi inceleyerek en kısa sürede sizinle iletişime geçecektir.",home:"Ana sayfaya dön",whatsapp:"WhatsApp’tan hemen yazın"},
 en:{title1:"Let's take the",title2:"first step together.",lead:"Complete the form and our team will review your request and contact you as soon as possible.",point1:"We listen to your needs",point2:"We identify the right path",point3:"We offer a clear plan",thanksKicker:"REQUEST RECEIVED",thanksTitle:"Thank you.",thanksBody:"Our team will review your request and contact you as soon as possible.",home:"Back to home",whatsapp:"Message us on WhatsApp"},
 ru:{title1:"Сделаем первый шаг",title2:"вместе.",lead:"Заполните форму: команда рассмотрит запрос и свяжется с вами как можно скорее.",point1:"Выслушаем ваши потребности",point2:"Определим подходящий путь",point3:"Предложим ясный план",thanksKicker:"ЗАПРОС ПОЛУЧЕН",thanksTitle:"Спасибо.",thanksBody:"Мы рассмотрим ваш запрос и свяжемся с вами как можно скорее.",home:"На главную",whatsapp:"Написать в WhatsApp"},
 ar:{title1:"لنبدأ الخطوة الأولى",title2:"معاً.",lead:"املأ النموذج وسيراجع فريقنا طلبك ويتواصل معك في أقرب وقت.",point1:"نستمع إلى احتياجاتك",point2:"نحدد المسار المناسب",point3:"نقدم خطة واضحة",thanksKicker:"تم استلام الطلب",thanksTitle:"شكراً لك.",thanksBody:"سيراجع فريقنا طلبك ويتواصل معك في أقرب وقت.",home:"العودة للرئيسية",whatsapp:"راسلنا عبر واتساب"}
} as const;
export function requestText(locale:string){return requestLabels[(locale in requestLabels?locale:"tr") as Locale]}
