import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { getCatalogProgramCounts,getCatalogProgramTotal,getCatalogUniversities,getFaqs,getServices,getSettings,searchCatalogPrograms } from "@/lib/content";
import { localizeFaqs,localizeService } from "@/lib/i18n";

const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
const normalize=(value:string)=>value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9ğüşöçıİâîû ]/gi," ").replace(/\s+/g," ").trim();
const stop=new Set(["bir","ve","ile","icin","için","mi","mu","mı","mü","ne","nasil","nasıl","nedir","hakkinda","the","and","for","what","how"]);
type HistoryItem={role:"assistant"|"user";text:string};
const hasAny=(text:string,needles:string[])=>needles.some(item=>text.includes(item));

export async function POST(request:Request){
  if(!request.headers.get("content-type")?.includes("application/json"))return NextResponse.json({error:"Geçersiz istek."},{status:415});
  const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({error:"İstek doğrulanamadı."},{status:403});
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null,question=clean(body?.question,500),locale=clean(body?.locale,5)||"tr";
  if(question.length<2)return NextResponse.json({error:"Lütfen sorunuzu yazın."},{status:400});
  const history=Array.isArray(body?.history)?body.history.slice(-8).map(item=>{const value=item as Partial<HistoryItem>;return {role:value.role==="user"?"user":"assistant",text:clean(value.text,500)}}).filter(item=>item.text):[];
  const [rawFaqs,services,settings,universities]=await Promise.all([getFaqs(),getServices(),getSettings(),getCatalogUniversities()]),faqs=localizeFaqs(locale,rawFaqs),serviceCopy=services.map(item=>localizeService(locale,item));
  const cityCount=new Set(universities.map(item=>item.city)).size,programTotal=getCatalogProgramTotal();
  const context=[`İletişim: ${settings.phone} · ${settings.email} · WhatsApp ${settings.whatsapp}\nAdres: ${settings.address}`,`Katalog: ${universities.length} üniversite, ${programTotal} program, ${cityCount} şehir`,...faqs.map(item=>`Soru: ${item.question}\nYanıt: ${item.answer}`),...serviceCopy.map(item=>`Hizmet: ${item.title}\nBilgi: ${item.summary}`)].join("\n\n");
  const key=(env as unknown as {OPENAI_API_KEY?:string}).OPENAI_API_KEY;
  if(key){try{const conversation=history.map(item=>`${item.role==="user"?"Kullanıcı":"Asistan"}: ${item.text}`).join("\n");const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-6-astra",reasoning:{effort:"low"},store:false,max_output_tokens:520,instructions:"Sen TD Danışmanlık web sitesi asistanısın. Yalnızca verilen site bilgisine dayan. Kesin kabul, süre, fiyat veya hukuki sonuç garantisi verme. Kullanıcının sorusuna önce doğrudan cevap ver, ardından uygulanabilir sonraki adımı söyle. Kullanıcı eksik bilgi verdiyse tek bir kısa takip sorusu sor. Bilgi yoksa bunu açıkça söyle ve danışmanla görüşmeye yönlendir. Kullanıcının dilinde doğal, profesyonel ve pratik yanıt ver.",input:`Site bilgisi:\n${context}\n\nSon konuşma:\n${conversation||"Yeni konuşma"}\n\nKullanıcı sorusu: ${question}`})});if(response.ok){const data=await response.json() as {output?:Array<{content?:Array<{type?:string;text?:string}>}>};const answer=data.output?.flatMap(item=>item.content||[]).find(item=>item.type==="output_text")?.text?.trim();if(answer)return NextResponse.json({answer,mode:"ai"})}}catch{/* Aşağıdaki doğrulanmış site bilgi tabanına geç. */}}

  const normalized=normalize(question),previousUser=history.filter(item=>item.role==="user").at(-1)?.text||"",conversationText=normalize(`${previousUser} ${question}`),contact=`${settings.phone} numaralı telefondan, ${settings.email} adresinden veya WhatsApp üzerinden bize ulaşabilirsiniz. Ofis adresimiz: ${settings.address}.`;
  if(locale==="tr"){
    if(hasAny(normalized,["merhaba","selam","iyi gunler","iyi aksamlar"]))return NextResponse.json({answer:"Merhaba. Üniversite ve bölüm seçimi, başvuru-kayıt, ikamet, çalışma izni, tercüme veya denklik konularından hangisiyle ilgileniyorsunuz?",mode:"knowledge"});
    if(hasAny(normalized,["tesekkur","sağ ol","sagol","gorusuruz"]))return NextResponse.json({answer:"Rica ederim. Üniversite, bölüm veya resmî işlemle ilgili başka bir sorunuz olursa buradayım.",mode:"knowledge"});
    if(hasAny(normalized,["telefon","numara","whatsapp","mail","e posta","adres","neredesiniz","iletisim"])&&!hasAny(normalized,["adres kayit","adres kayıt","nufus adres"]))return NextResponse.json({answer:contact,mode:"knowledge"});
    if(hasAny(normalized,["mesai","calisma saati","kacta acik","kacta kapaniyor"]))return NextResponse.json({answer:`Çalışma saatleri: ${settings.hours}. Gelmeden önce telefon veya WhatsApp üzerinden randevu teyidi almanız iyi olur.`,mode:"knowledge"});
    if(hasAny(normalized,["kac universite","universite sayisi","kac okul","katalogda kac"]))return NextResponse.json({answer:`Katalogda Türkiye genelinde ${universities.length} üniversite ve ${cityCount} şehir bulunuyor. Üniversiteler sayfasında “Tümü”, şehir ve kurum türü filtrelerini birlikte kullanabilirsiniz.`,mode:"knowledge"});
    if(hasAny(normalized,["kac bolum","kac program","program sayisi"]))return NextResponse.json({answer:`Katalogda ${programTotal} program bulunuyor. Bölümler sayfasında arama yapabilir; Ön Lisans, Lisans, Yüksek Lisans ve Doktora sekmeleriyle sonuçları ayırabilirsiniz.`,mode:"knowledge"});
    if(hasAny(normalized,["tercih robotu","bana bolum bul","hangi bolumu sec","hangi bolum uygun","tercih yap"]))return NextResponse.json({answer:"Menüdeki Tercih Robotu; eğitim düzeyi, alan, şehir ve eğitim diline göre seçenekleri daraltır. Bu dört bilgiyi seçtikten sonra sizi filtrelenmiş bölüm listesine götürür. Kararsızsanız önce eğitim düzeyinizi ve ilgilendiğiniz alanı seçmeniz yeterli.",mode:"knowledge"});
    if(hasAny(normalized,["nasil basvur","universite basvuru","basvuru sureci","kayit nasil","kabul nasil"]))return NextResponse.json({answer:"Önce hedef program ve üniversite belirlenir; ardından diploma/transkript, pasaport, dil belgesi ve kuruma özel evraklar kontrol edilir. Başvuru takvimi üniversiteye göre değişir. Belgelerinizi ve hedef döneminizi yazarsanız size daha net bir kontrol listesi çıkarabiliriz.",mode:"knowledge"});
    if(hasAny(normalized,["hangi belge","gerekli belgeler","evrak","diploma","transkript"]))return NextResponse.json({answer:"Üniversite başvurularında çoğunlukla pasaport, diploma, transkript, fotoğraf ve istenirse dil ya da sınav sonucu gerekir. Yüksek lisans ve doktorada niyet mektubu, referans ve özgeçmiş de istenebilir. Kesin liste program ve üniversiteye göre değişir.",mode:"knowledge"});
    if(hasAny(normalized,["yos","sat","sinav puani","diploma notu","taban puan","kac puan"]))return NextResponse.json({answer:"Kabul yöntemi üniversite ve programa göre değişir; bazı kurumlar TR-YÖS/SAT gibi sonuçları, bazıları diploma notunu değerlendirir. Tek bir geçerli taban puan yoktur. Üniversite ve bölüm adını yazarsanız doğru kabul yolunu ayıralım.",mode:"knowledge"});
    if(hasAny(normalized,["dil belgesi","toefl","ielts","tomerde","tomer","hazirlik","turkce yeterlilik","ingilizce yeterlilik"]))return NextResponse.json({answer:"Dil şartı programın eğitim diline göre belirlenir. Kabul edilen sınavlar ve minimum puanlar üniversiteden üniversiteye değişir; belge yoksa hazırlık veya kurum sınavı seçeneği bulunabilir. Seçtiğiniz programın güncel şartını kontrol etmek gerekir.",mode:"knowledge"});
    if(hasAny(normalized,["son tarih","basvuru tarihi","ne zaman basvur","takvim","deadline"]))return NextResponse.json({answer:"Başvuru tarihleri üniversiteye, programa ve döneme göre farklıdır; tek bir genel son tarih yoktur. İlgilendiğiniz üniversite, bölüm ve hedef dönemi yazın; güncel resmî takvimi esas alarak ilerleyelim.",mode:"knowledge"});
    if(hasAny(normalized,["fiyat","ucret","harc","taksit","burs","indirim"]))return NextResponse.json({answer:"Ücret, burs ve taksit seçenekleri üniversiteye, programa, vatandaşlığa ve döneme göre değişebilir. Bölüm detayındaki tutarı ön bilgi kabul edin; ödeme yapmadan önce üniversitenin güncel resmî teklifini ve iade koşullarını doğrulayın.",mode:"knowledge"});
    if(hasAny(normalized,["yatay gecis","transfer","ders saydir","kredi transfer"]))return NextResponse.json({answer:"Yatay geçiş ve ders saydırma; transkript, ders içerikleri, kredi uyumu, kontenjan ve üniversitenin yönetmeliğine göre değerlendirilir. Kesin karar ilgili üniversitenindir. Mevcut okulunuzu, sınıfınızı ve hedef programı yazarsanız olası yolu netleştirebiliriz.",mode:"knowledge"});
    if(hasAny(normalized,["master","yuksek lisans"]))return NextResponse.json({answer:"Yüksek lisans programlarını Bölümler sayfasındaki “Yüksek Lisans” sekmesinden ayırabilirsiniz. Başvuruda diploma, transkript, özgeçmiş, niyet mektubu, referans ve dil belgesi istenebilir; şartlar programa göre değişir.",mode:"knowledge"});
    if(hasAny(normalized,["doktora","phd"]))return NextResponse.json({answer:"Doktora programlarını Bölümler sayfasındaki “Doktora” sekmesinden ayırabilirsiniz. Genellikle lisansüstü diploma, araştırma önerisi, referans, özgeçmiş ve dil belgesi değerlendirilir; kesin koşullar programa aittir.",mode:"knowledge"});
    if(hasAny(normalized,["ikamet","oturma izni","residence"]))return NextResponse.json({answer:"Öğrenci ikamet süreci; geçerli pasaport, öğrenci belgesi, adres, sağlık sigortası ve başvuru kayıtları gibi belgelere dayanır. Belge listesi ve teslim yöntemi güncel uygulamaya göre değişebilir; kişisel durumunuzu görmeden kesin süre veya sonuç veremeyiz.",mode:"knowledge"});
    if(hasAny(normalized,["calisma izni","çalışma izni","work permit"]))return NextResponse.json({answer:"Çalışma izni çoğunlukla işveren, iş sözleşmesi ve başvuru sahibinin statüsüne bağlı bir süreçtir. Öğrenci olmak tek başına otomatik izin sağlamaz. İşvereninizi ve mevcut ikamet durumunuzu yazarsanız hangi yolun değerlendirileceğini açıklayabiliriz.",mode:"knowledge"});
    if(hasAny(normalized,["vatandaslik","vatandaşlık","citizenship"]))return NextResponse.json({answer:"Vatandaşlık başvurusu; başvuru türü, ikamet geçmişi, yatırım veya aile bağı gibi hukuki dayanağa göre değişir. Sitedeki bilgi genel yönlendirmedir; uygunluk ve belge listesi dosya özelinde incelenmelidir.",mode:"knowledge"});
    if(hasAny(normalized,["denklik","yok denklik","diploma tanima","diploma tanınma"]))return NextResponse.json({answer:"Denklik gerekip gerekmediği, diplomanın kullanılacağı işleme ve kuruma göre değişir. Eğitim seviyesi, ülke, bölüm ve kullanım amacını yazın; YÖK veya ilgili kurumun güncel şartına göre yol haritası çıkaralım.",mode:"knowledge"});
    if(hasAny(normalized,["tercume","çeviri","ceviri","noter","apostil"]))return NextResponse.json({answer:"Tercüme, noter onayı ve apostil gerekliliği belgenin düzenlendiği ülkeye ve sunulacağı kuruma göre değişir. Gereksiz masraf olmaması için önce kurumun güncel belge listesini, sonra onay zincirini kontrol etmek gerekir.",mode:"knowledge"});
    if(hasAny(normalized,["adres kayit","adres kayıt","nufus adres"]))return NextResponse.json({answer:"Adres kaydı için istenen belge ve randevu adımı kişinin ikamet statüsüne ve beyan edilen adrese göre değişebilir. Kira sözleşmesi, fatura veya ek teyit belgesi gerekebilir; güncel kurum uygulaması esas alınır.",mode:"knowledge"});
    if(hasAny(normalized,["garanti","kesin kabul","kesin cikar","kesin çıkar"]))return NextResponse.json({answer:"Hayır; kabul, ikamet veya diğer resmî işlemlerde sonuç garantisi verilemez. Kararı üniversite ya da yetkili kurum verir. Biz doğru seçenek, belge kontrolü ve süreç takibi konusunda destek oluruz.",mode:"knowledge"});
    if(hasAny(normalized,["canli destek","insan","danisman","sizi arasin","gorusmek","randevu"]))return NextResponse.json({answer:`Bir danışmanla görüşmek için WhatsApp üzerinden yazabilir veya ${settings.phone} numarasını arayabilirsiniz. Hedefinizi, eğitim düzeyinizi ve ilgilendiğiniz şehir ya da bölümü kısaca yazmanız görüşmeyi hızlandırır.`,mode:"knowledge"});

    const namedUniversity=universities.find(item=>normalized.includes(normalize(item.name)));
    if(namedUniversity){const count=getCatalogProgramCounts()[namedUniversity.slug]||0;return NextResponse.json({answer:`${namedUniversity.name}, ${namedUniversity.city} ilinde bulunan ${namedUniversity.institutionType.toLocaleLowerCase("tr-TR")} üniversitesidir. Katalogda bu üniversiteye ait ${count} program var. Üniversiteler sayfasından kurumu açarak bölümleri inceleyebilir; kesin ücret ve kabul koşulunu güncel resmî duyurudan doğrulayabilirsiniz.`,mode:"knowledge"});}
    const programTopics:Array<[string,string]>=[["bilgisayar muhendisligi","Bilgisayar Mühendisliği"],["tip","Tıp"],["dis hekimligi","Diş Hekimliği"],["eczacilik","Eczacılık"],["hukuk","Hukuk"],["psikoloji","Psikoloji"],["mimarlik","Mimarlık"],["isletme","İşletme"],["hemsirelik","Hemşirelik"]];
    const topic=programTopics.find(([needle])=>normalized.includes(needle));
    if(topic){const result=await searchCatalogPrograms({query:topic[1],sort:"degree",pageSize:12});const samples=result.programs.slice(0,3).map(item=>`${item.name} (${item.degreeType}) — ${item.universityName}`).join("; ");return NextResponse.json({answer:result.total?`${topic[1]} aramasıyla katalogda ${result.total} program bulundu. İlk örnekler: ${samples}. Bölümler sayfasındaki arama ve eğitim düzeyi sekmeleriyle listeyi daraltabilirsiniz.`:`${topic[1]} için katalogda doğrudan eşleşme bulamadım. Bölümler sayfasında farklı yazım veya alan filtresiyle arayın; güncel programı üniversitenin resmî kaynağından da doğrulayın.`,mode:"knowledge"});}
  }

  const terms=conversationText.split(/\s+/).filter(term=>term.length>2&&!stop.has(term));let best:{score:number;answer:string}|null=null;
  for(const item of faqs){const title=normalize(item.question),haystack=normalize(`${item.question} ${item.answer} ${item.category}`);const score=terms.reduce((total,term)=>total+(title.includes(term)?3:haystack.includes(term)?1:0),0)+(normalized.length>8&&title.includes(normalized)?8:0);if(!best||score>best.score)best={score,answer:item.answer}}
  for(const item of serviceCopy){const title=normalize(item.title),haystack=normalize(`${item.title} ${item.summary}`);const score=terms.reduce((total,term)=>total+(title.includes(term)?3:haystack.includes(term)?1:0),0);if(!best||score>best.score)best={score,answer:`${item.summary} İsterseniz durumunuza göre gerekli belgeleri ve sonraki adımı birlikte netleştirebiliriz.`}}
  const generic=locale==="en"?"I could not find a definitive answer in the site information. Tell me the university, program or procedure you are interested in, or contact an adviser for a case-specific review.":locale==="ru"?"В информации сайта нет точного ответа. Укажите университет, программу или процедуру либо свяжитесь с консультантом для оценки вашей ситуации.":locale==="ar"?"لم أجد إجابة مؤكدة ضمن معلومات الموقع. اذكر الجامعة أو التخصص أو الإجراء الذي تقصده، أو تواصل مع مستشار لتقييم حالتك.":"Bu konuda kesin bir yanıt verebilmem için ilgilendiğiniz üniversiteyi, bölümü veya işlemi biraz daha açık yazın. Dosyanıza özel değerlendirme için danışmanımıza da ulaşabilirsiniz.";
  return NextResponse.json({answer:best&&best.score>=2?best.answer:generic,mode:"knowledge"});
}
