import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { getCatalogProgramTotal,getCatalogUniversities,getFaqs,getServices,getSettings } from "@/lib/content";
import { localizeFaqs,localizeService } from "@/lib/i18n";

const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
const normalize=(value:string)=>value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9ğüşöçıİâîû ]/gi," ");
const stop=new Set(["bir","ve","ile","icin","için","mi","mu","mı","mü","ne","nasil","nasıl","the","and","for","what","how"]);
type HistoryItem={role:"assistant"|"user";text:string};
const hasAny=(text:string,needles:string[])=>needles.some(item=>text.includes(item));

export async function POST(request:Request){
  if(!request.headers.get("content-type")?.includes("application/json"))return NextResponse.json({error:"Geçersiz istek."},{status:415});
  const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({error:"İstek doğrulanamadı."},{status:403});
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null,question=clean(body?.question,500),locale=clean(body?.locale,5)||"tr";
  if(question.length<2)return NextResponse.json({error:"Lütfen sorunuzu yazın."},{status:400});
  const history=Array.isArray(body?.history)?body.history.slice(-6).map(item=>{const value=item as Partial<HistoryItem>;return {role:value.role==="user"?"user":"assistant",text:clean(value.text,500)}}).filter(item=>item.text):[];
  const [rawFaqs,services,settings,universities]=await Promise.all([getFaqs(),getServices(),getSettings(),getCatalogUniversities()]),faqs=localizeFaqs(locale,rawFaqs),serviceCopy=services.map(item=>localizeService(locale,item));
  const cityCount=new Set(universities.map(item=>item.city)).size;
  const context=[`İletişim: ${settings.phone} · ${settings.email} · WhatsApp ${settings.whatsapp}\nAdres: ${settings.address}`,`Katalog: ${universities.length} üniversite, ${getCatalogProgramTotal()} program, ${cityCount} şehir`,...faqs.map(item=>`Soru: ${item.question}\nYanıt: ${item.answer}`),...serviceCopy.map(item=>`Hizmet: ${item.title}\nBilgi: ${item.summary}`)].join("\n\n");
  const key=(env as unknown as {OPENAI_API_KEY?:string}).OPENAI_API_KEY;
  if(key){try{const conversation=history.map(item=>`${item.role==="user"?"Kullanıcı":"Asistan"}: ${item.text}`).join("\n");const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-6-astra",reasoning:{effort:"low"},store:false,max_output_tokens:420,instructions:"Sen TD Danışmanlık web sitesi asistanısın. Yalnızca verilen site bilgisine dayan. Kesin kabul, süre, fiyat veya hukuki sonuç garantisi verme. Kullanıcı eksik bilgi verdiyse tek bir kısa takip sorusu sor. Bilgi yoksa bunu açıkça söyle ve danışmanla görüşmeye yönlendir. Kullanıcının dilinde doğal, profesyonel ve pratik bir yanıt ver.",input:`Site bilgisi:\n${context}\n\nSon konuşma:\n${conversation||"Yeni konuşma"}\n\nKullanıcı sorusu: ${question}`})});if(response.ok){const data=await response.json() as {output?:Array<{content?:Array<{type?:string;text?:string}>}>};const answer=data.output?.flatMap(item=>item.content||[]).find(item=>item.type==="output_text")?.text?.trim();if(answer)return NextResponse.json({answer,mode:"ai"})}}catch{/* Fall back to the verified site knowledge below. */}}
  const normalized=normalize(question),contact=`${settings.phone} numaralı telefondan, ${settings.email} adresinden veya WhatsApp üzerinden bize ulaşabilirsiniz. Ofis adresimiz: ${settings.address}.`;
  if(locale==="tr"){
    if(hasAny(normalized,["merhaba","selam","iyi gunler","iyi aksamlar"]))return NextResponse.json({answer:"Merhaba. Üniversite ve bölüm seçimi, başvuru-kayıt, ikamet, çalışma izni, tercüme veya denklik konularından hangisiyle ilgileniyorsunuz?",mode:"knowledge"});
    if(hasAny(normalized,["telefon","numara","whatsapp","mail","e posta","adres","neredesiniz","iletisim"]))return NextResponse.json({answer:contact,mode:"knowledge"});
    if(hasAny(normalized,["kac universite","universite sayisi","kac okul","katalogda kac"]))return NextResponse.json({answer:`Katalogda Türkiye genelinde ${universities.length} üniversite ve ${cityCount} şehir bulunuyor. Şehir, kurum türü ve kuruluş yılına göre filtreleyebilirsiniz.`,mode:"knowledge"});
    if(hasAny(normalized,["kac bolum","kac program","program sayisi"]))return NextResponse.json({answer:`Katalogda ${getCatalogProgramTotal()} program bulunuyor. Bölüm adı, şehir, üniversite, derece, eğitim dili ve alana göre filtreleme yapabilirsiniz.`,mode:"knowledge"});
    if(hasAny(normalized,["fiyat","ucret","taksit","burs"]))return NextResponse.json({answer:"Ücret ve burs bilgileri üniversiteye, programa ve döneme göre değişir. Bölüm sayfasındaki bilgiyi başlangıç olarak kullanın; kesin tutarı başvuru öncesinde üniversitenin güncel resmî duyurusundan doğrulayalım.",mode:"knowledge"});
    if(hasAny(normalized,["canli destek","insan","danisman","sizi arasin","gorusmek"]))return NextResponse.json({answer:`Bir danışmanla görüşmek için WhatsApp üzerinden yazabilir veya ${settings.phone} numarasını arayabilirsiniz. Kısaca hedefinizi ve ilgilendiğiniz şehir ya da bölümü yazmanız süreci hızlandırır.`,mode:"knowledge"});
  }
  const terms=normalized.split(/\s+/).filter(term=>term.length>2&&!stop.has(term));let best:{score:number;answer:string}|null=null;for(const item of faqs){const title=normalize(item.question),haystack=normalize(`${item.question} ${item.answer} ${item.category}`);const score=terms.reduce((total,term)=>total+(title.includes(term)?3:haystack.includes(term)?1:0),0)+(normalized.length>8&&title.includes(normalized)?8:0);if(!best||score>best.score)best={score,answer:item.answer}}for(const item of serviceCopy){const title=normalize(item.title),haystack=normalize(`${item.title} ${item.summary}`);const score=terms.reduce((total,term)=>total+(title.includes(term)?3:haystack.includes(term)?1:0),0);if(!best||score>best.score)best={score,answer:`${item.summary} İsterseniz durumunuza göre gerekli belgeleri ve sonraki adımı birlikte netleştirebiliriz.`}}const generic=locale==="en"?"I could not find a definitive answer in the site information. Tell me the university, program or procedure you are interested in, or contact an adviser for a case-specific review.":locale==="ru"?"В информации сайта нет точного ответа. Укажите университет, программу или процедуру либо свяжитесь с консультантом для оценки вашей ситуации.":locale==="ar"?"لم أجد إجابة مؤكدة ضمن معلومات الموقع. اذكر الجامعة أو التخصص أو الإجراء الذي تقصده، أو تواصل مع مستشار لتقييم حالتك.":"Bu konuda kesin bir yanıt verebilmem için ilgilendiğiniz üniversiteyi, bölümü veya işlemi biraz daha açık yazın. Dosyanıza özel değerlendirme için danışmanımıza da ulaşabilirsiniz.";return NextResponse.json({answer:best&&best.score>=2?best.answer:generic,mode:"knowledge"});
}
