/* eslint-disable @next/next/no-img-element -- The service visual uses the admin-managed Site image URL. */
import { notFound } from "next/navigation";
import Link from "@/components/NativeLink";
import { InnerPage } from "@/components/InnerPage";
import { getService, getServices, getSettings } from "@/lib/content";
import { languageLabels, localizeService, serviceDetailText } from "@/lib/i18n";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}){const {slug}=await params;const service=await getService(slug);if(!service)return{};const title=`${service.title} | TD Danışmanlık`;return{title,description:service.summary,openGraph:{title,description:service.summary,images:[]},twitter:{card:"summary",title,description:service.summary,images:[]}}}
export default async function ServicePage({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;const [settings,service,all]=await Promise.all([getSettings(),getService(slug),getServices()]);if(!service)notFound();const t=languageLabels(locale),detail=serviceDetailText(locale),display=localizeService(locale,service),steps=detail.steps;return <InnerPage settings={settings} locale={locale} crumbs={[{label:t.home,href:`/${locale}`},{label:t.services,href:`/${locale}/hizmetler`},{label:display.title}]}><main className="detail-page"><section className="detail-hero"><div><p className="section-index">{t.services} / {service.icon}</p><h1>{display.title}</h1><p>{display.summary}</p><Link className="button button-primary" href={`/${locale}/danismanlik-talebi`}>{detail.consult}</Link></div><aside className="detail-brand-panel"><img src={service.image} alt="" aria-hidden="true"/><div className="detail-panel-wordmark" aria-label={settings.siteName}><strong>TD</strong><b>{settings.siteName.replace(/^TD\s+/i,"")}</b></div><p>{detail.tagline}<small>{detail.subtag}</small></p></aside></section><section className="detail-content"><article><p className="section-index">{detail.scope}</p><h2>{detail.scopeTitle}</h2><p>{display.detail}</p><p>{detail.note}</p></article><aside><h3>{detail.how}</h3>{steps.map((s,i)=><div key={s}><span>0{i+1}</span><p>{s}</p></div>)}</aside></section><section className="related-section"><p className="section-index">{detail.related}</p><div>{all.filter(s=>s.id!==service.id).slice(0,3).map(s=><Link key={s.id} href={`/${locale}/hizmetler/${s.slug}`}><span>{s.icon}</span><h3>{localizeService(locale,s).title}</h3></Link>)}</div></section></main></InnerPage>}
